export const CountryList = {
  GH: {
    code_2: 'GH',
    code_3: 'GHA',
    name: '가나',
    name_en: 'GHANA',
    name_origin: 'Ghana',
    flag_path: 'gh.png',
    tel_code: '+233',
  },
  GA: {
    code_2: 'GA',
    code_3: 'GAB',
    name: '가봉',
    name_en: 'GABON',
    name_origin: 'Gabon',
    flag_path: 'ga.png',
    tel_code: '+241',
  },
  GY: {
    code_2: 'GY',
    code_3: 'GUY',
    name: '가이아나',
    name_en: 'GUYANA',
    name_origin: 'Guyana',
    flag_path: 'gy.png',
    tel_code: '+592',
  },
  GM: {
    code_2: 'GM',
    code_3: 'GMB',
    name: '감비아',
    name_en: 'GAMBIA',
    name_origin: 'Gambia',
    flag_path: 'gm.png',
    tel_code: '+220',
  },
  GG: {
    code_2: 'GG',
    code_3: 'GGY',
    name: '건지 섬',
    name_en: 'GUERNSEY',
    name_origin: 'Guernsey',
    flag_path: 'GG.png',
    tel_code: '+441481',
  },
  GP: {
    code_2: 'GP',
    code_3: 'GLP',
    name: '과들루프',
    name_en: 'GUADELOUPE',
    name_origin: 'Guadeloupe',
    flag_path: 'GP.png',
    tel_code: '+590',
  },
  GT: {
    code_2: 'GT',
    code_3: 'GTM',
    name: '과테말라',
    name_en: 'GUATEMALA',
    name_origin: 'Guatemala',
    flag_path: 'GT.png',
    tel_code: '+502',
  },
  GU: {
    code_2: 'GU',
    code_3: 'GUM',
    name: '괌',
    name_en: 'GUAM',
    name_origin: 'Guam',
    flag_path: 'GU.png',
    tel_code: '+1671',
  },
  GD: {
    code_2: 'GD',
    code_3: 'GRD',
    name: '그레나다',
    name_en: 'GRENADA',
    name_origin: 'Grenada',
    flag_path: 'GD.png',
    tel_code: '+1473',
  },
  GR: {
    code_2: 'GR',
    code_3: 'GRC',
    name: '그리스',
    name_en: 'GREECE',
    name_origin: 'Ελλάς',
    flag_path: 'GR.png',
    tel_code: '+30',
  },
  GL: {
    code_2: 'GL',
    code_3: 'GRL',
    name: '그린란드',
    name_en: 'GREENLAND',
    name_origin: 'Greenland',
    flag_path: 'GL.png',
    tel_code: '+299',
  },
  GN: {
    code_2: 'GN',
    code_3: 'GIN',
    name: '기니',
    name_en: 'GUINEA',
    name_origin: 'Guinée',
    flag_path: 'GN.png',
    tel_code: '+224',
  },
  GW: {
    code_2: 'GW',
    code_3: 'GNB',
    name: '기니비사우',
    name_en: 'GUINEA-BISSAU',
    name_origin: 'Guiné-Bissau',
    flag_path: 'GW.png',
    tel_code: '+245',
  },
  NA: {
    code_2: 'NA',
    code_3: 'NAM',
    name: '나미비아',
    name_en: 'NAMIBIA',
    name_origin: 'Namibia',
    flag_path: 'NA.png',
    tel_code: '+264',
  },
  NR: {
    code_2: 'NR',
    code_3: 'NRU',
    name: '나우루',
    name_en: 'NAURU',
    name_origin: 'Naoero',
    flag_path: 'NR.png',
    tel_code: '+674',
  },
  NG: {
    code_2: 'NG',
    code_3: 'NGA',
    name: '나이지리아',
    name_en: 'NIGERIA',
    name_origin: 'Nigeria',
    flag_path: 'NG.png',
    tel_code: '+234',
  },
  AQ: {
    code_2: 'AQ',
    code_3: 'ATA',
    name: '남극',
    name_en: 'ANTARCTICA',
    name_origin: 'Antarctica',
    flag_path: 'AQ.png',
    tel_code: '+6721',
  },
  SS: {
    code_2: 'SS',
    code_3: 'SSD',
    name: '남수단',
    name_en: 'REPUBLIC OF SOUTH SUDAN',
    name_origin: 'South Sudan',
    flag_path: 'SS.png',
    tel_code: '+211',
  },
  ZA: {
    code_2: 'ZA',
    code_3: 'ZAF',
    name: '남아프리카 공화국',
    name_en: 'SOUTH AFRICA',
    name_origin: 'South Africa',
    flag_path: 'ZA.png',
    tel_code: '+27',
  },
  NL: {
    code_2: 'NL',
    code_3: 'NLD',
    name: '네덜란드',
    name_en: 'NETHERLANDS',
    name_origin: 'Nederland',
    flag_path: 'NL.png',
    tel_code: '+31',
  },
  AN: {
    code_2: 'AN',
    code_3: 'ANT',
    name: '네덜란드령 안틸레스',
    name_en: 'NETHERLANDS ANTILLES',
    name_origin: 'Netherlands Antilles',
    flag_path: 'AN.png',
    tel_code: '+599',
  },
  NP: {
    code_2: 'NP',
    code_3: 'NPL',
    name: '네팔',
    name_en: 'NEPAL',
    name_origin: 'नेपाल',
    flag_path: 'NP.png',
    tel_code: '+977',
  },
  NO: {
    code_2: 'NO',
    code_3: 'NOR',
    name: '노르웨이',
    name_en: 'NORWAY',
    name_origin: 'Norge',
    flag_path: 'NO.png',
    tel_code: '+47',
  },
  NF: {
    code_2: 'NF',
    code_3: 'NFK',
    name: '노퍽 섬',
    name_en: 'NORFOLK ISLAND',
    name_origin: 'Norfolk Island',
    flag_path: 'NF.png',
    tel_code: '+6723',
  },
  NC: {
    code_2: 'NC',
    code_3: 'NCL',
    name: '누벨칼레도니',
    name_en: 'NEW CALEDONIA',
    name_origin: 'New Caledonia',
    flag_path: 'NC.png',
    tel_code: '+687',
  },
  NZ: {
    code_2: 'NZ',
    code_3: 'NZL',
    name: '뉴질랜드',
    name_en: 'NEW ZEALAND',
    name_origin: 'New Zealand',
    flag_path: 'NZ.png',
    tel_code: '+64',
  },
  NU: {
    code_2: 'NU',
    code_3: 'NIU',
    name: '니우에',
    name_en: 'NIUE',
    name_origin: 'Niue',
    flag_path: 'NU.png',
    tel_code: '+683',
  },
  NE: {
    code_2: 'NE',
    code_3: 'NER',
    name: '니제르',
    name_en: 'NIGER',
    name_origin: 'Niger',
    flag_path: 'NE.png',
    tel_code: '+227',
  },
  NI: {
    code_2: 'NI',
    code_3: 'NIC',
    name: '니카라과',
    name_en: 'NICARAGUA',
    name_origin: 'Nicaragua',
    flag_path: 'NI.png',
    tel_code: '+505',
  },
  KR: {
    code_2: 'KR',
    code_3: 'KOR',
    name: '대한민국',
    name_en: 'KOREA, REPUBLIC OF',
    name_origin: '한국',
    flag_path: 'KR.png',
    tel_code: '+82',
  },
  DK: {
    code_2: 'DK',
    code_3: 'DNK',
    name: '덴마크',
    name_en: 'DENMARK',
    name_origin: 'Danmark',
    flag_path: 'DK.png',
    tel_code: '+45',
  },
  DO: {
    code_2: 'DO',
    code_3: 'DOM',
    name: '도미니카 공화국',
    name_en: 'DOMINICAN REPUBLIC',
    name_origin: 'Dominican Republic',
    flag_path: 'DO.png',
    tel_code: '+1809',
  },
  DM: {
    code_2: 'DM',
    code_3: 'DMA',
    name: '도미니카 연방',
    name_en: 'DOMINICA',
    name_origin: 'Dominica',
    flag_path: 'DM.png',
    tel_code: '+1767',
  },
  DE: {
    code_2: 'DE',
    code_3: 'DEU',
    name: '독일',
    name_en: 'GERMANY',
    name_origin: 'Deutschland',
    flag_path: 'DE.png',
    tel_code: '+49',
  },
  TL: {
    code_2: 'TL',
    code_3: 'TLS',
    name: '동티모르',
    name_en: 'EAST TIMOR',
    name_origin: 'Timor-Leste',
    flag_path: 'TL.png',
    tel_code: '+670',
  },
  LA: {
    code_2: 'LA',
    code_3: 'LAO',
    name: '라오스',
    name_en: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    name_origin: 'ນລາວ',
    flag_path: 'LA.png',
    tel_code: '+856',
  },
  LR: {
    code_2: 'LR',
    code_3: 'LBR',
    name: '라이베리아',
    name_en: 'LIBERIA',
    name_origin: 'Liberia',
    flag_path: 'LR.png',
    tel_code: '+231',
  },
  LV: {
    code_2: 'LV',
    code_3: 'LVA',
    name: '라트비아',
    name_en: 'LATVIA',
    name_origin: 'Latvija',
    flag_path: 'LV.png',
    tel_code: '+371',
  },
  RU: {
    code_2: 'RU',
    code_3: 'RUS',
    name: '러시아',
    name_en: 'RUSSIAN FEDERATION',
    name_origin: 'Россия',
    flag_path: 'RU.png',
    tel_code: '+7',
  },
  LB: {
    code_2: 'LB',
    code_3: 'LBN',
    name: '레바논',
    name_en: 'LEBANON',
    name_origin: 'لبنان',
    flag_path: 'LB.png',
    tel_code: '+961',
  },
  LS: {
    code_2: 'LS',
    code_3: 'LSO',
    name: '레소토',
    name_en: 'LESOTHO',
    name_origin: 'Lesotho',
    flag_path: 'LS.png',
    tel_code: '+266',
  },
  RE: {
    code_2: 'RE',
    code_3: 'REU',
    name: '레위니옹',
    name_en: 'REUNION',
    name_origin: 'Reunion',
    flag_path: 'RE.png',
    tel_code: '+262',
  },
  RO: {
    code_2: 'RO',
    code_3: 'ROU',
    name: '루마니아',
    name_en: 'ROMANIA',
    name_origin: 'România',
    flag_path: 'RO.png',
    tel_code: '+40',
  },
  LU: {
    code_2: 'LU',
    code_3: 'LUX',
    name: '룩셈부르크',
    name_en: 'LUXEMBOURG',
    name_origin: 'Lëtzebuerg',
    flag_path: 'LU.png',
    tel_code: '+352',
  },
  RW: {
    code_2: 'RW',
    code_3: 'RWA',
    name: '르완다',
    name_en: 'RWANDA',
    name_origin: 'Rwanda',
    flag_path: 'RW.png',
    tel_code: '+250',
  },
  LY: {
    code_2: 'LY',
    code_3: 'LBY',
    name: '리비아',
    name_en: 'LIBYAN ARAB JAMAHIRIYA',
    name_origin: 'ليبيا',
    flag_path: 'LY.png',
    tel_code: '+218',
  },
  LT: {
    code_2: 'LT',
    code_3: 'LTU',
    name: '리투아니아',
    name_en: 'LITHUANIA',
    name_origin: 'Lietuva',
    flag_path: 'LT.png',
    tel_code: '+370',
  },
  LI: {
    code_2: 'LI',
    code_3: 'LIE',
    name: '리히텐슈타인',
    name_en: 'LIECHTENSTEIN',
    name_origin: 'Liechtenstein',
    flag_path: 'LI.png',
    tel_code: '+423',
  },
  MG: {
    code_2: 'MG',
    code_3: 'MDG',
    name: '마다가스카르',
    name_en: 'MADAGASCAR',
    name_origin: 'Madagasikara',
    flag_path: 'MG.png',
    tel_code: '+261',
  },
  MQ: {
    code_2: 'MQ',
    code_3: 'MTQ',
    name: '마르티니크',
    name_en: 'MARTINIQUE',
    name_origin: 'Martinique',
    flag_path: 'MQ.png',
    tel_code: '+596',
  },
  MH: {
    code_2: 'MH',
    code_3: 'MHL',
    name: '마셜 제도',
    name_en: 'MARSHALL ISLANDS',
    name_origin: 'Marshall Islands',
    flag_path: 'MH.png',
    tel_code: '+692',
  },
  YT: {
    code_2: 'YT',
    code_3: 'MYT',
    name: '마요트',
    name_en: 'MAYOTTE',
    name_origin: 'Mayotte',
    flag_path: 'YT.png',
    tel_code: '+269',
  },
  MO: {
    code_2: 'MO',
    code_3: 'MAC',
    name: '마카오',
    name_en: 'MACAU',
    name_origin: 'Macao',
    flag_path: 'MO.png',
    tel_code: '+853',
  },
  MK: {
    code_2: 'MK',
    code_3: 'MKD',
    name: '마케도니아 공화국',
    name_en: 'REPUBLIC OF MACEDONIA',
    name_origin: 'Македонија',
    flag_path: 'MK.png',
    tel_code: '+389',
  },
  MW: {
    code_2: 'MW',
    code_3: 'MWI',
    name: '말라위',
    name_en: 'MALAWI',
    name_origin: 'Malawi',
    flag_path: 'MW.png',
    tel_code: '+265',
  },
  MY: {
    code_2: 'MY',
    code_3: 'MYS',
    name: '말레이시아',
    name_en: 'MALAYSIA',
    name_origin: 'Malaysia',
    flag_path: 'MY.png',
    tel_code: '+60',
  },
  ML: {
    code_2: 'ML',
    code_3: 'MLI',
    name: '말리',
    name_en: 'MALI',
    name_origin: 'Mali',
    flag_path: 'ML.png',
    tel_code: '+223',
  },
  IM: {
    code_2: 'IM',
    code_3: 'IMN',
    name: '맨 섬',
    name_en: 'ISLE OF MAN',
    name_origin: 'Isle of Man',
    flag_path: 'IM.png',
    tel_code: '+441624',
  },
  MX: {
    code_2: 'MX',
    code_3: 'MEX',
    name: '멕시코',
    name_en: 'MEXICO',
    name_origin: 'México',
    flag_path: 'MX.png',
    tel_code: '+52',
  },
  MC: {
    code_2: 'MC',
    code_3: 'MCO',
    name: '모나코',
    name_en: 'MONACO',
    name_origin: 'Monaco',
    flag_path: 'MC.png',
    tel_code: '+377',
  },
  MA: {
    code_2: 'MA',
    code_3: 'MAR',
    name: '모로코',
    name_en: 'MOROCCO',
    name_origin: 'المغرب',
    flag_path: 'MA.png',
    tel_code: '+212',
  },
  MU: {
    code_2: 'MU',
    code_3: 'MUS',
    name: '모리셔스',
    name_en: 'MAURITIUS',
    name_origin: 'Mauritius',
    flag_path: 'MU.png',
    tel_code: '+230',
  },
  MR: {
    code_2: 'MR',
    code_3: 'MRT',
    name: '모리타니',
    name_en: 'MAURITANIA',
    name_origin: 'موريتانيا',
    flag_path: 'MR.png',
    tel_code: '+222',
  },
  MZ: {
    code_2: 'MZ',
    code_3: 'MOZ',
    name: '모잠비크',
    name_en: 'MOZAMBIQUE',
    name_origin: 'Moçambique',
    flag_path: 'MZ.png',
    tel_code: '+258',
  },
  ME: {
    code_2: 'ME',
    code_3: 'MNE',
    name: '몬테네그로',
    name_en: 'MONTENEGRO',
    name_origin: 'Црна Гора',
    flag_path: 'ME.png',
    tel_code: '+382',
  },
  MS: {
    code_2: 'MS',
    code_3: 'MSR',
    name: '몬트세랫',
    name_en: 'MONTSERRAT',
    name_origin: 'Montserrat',
    flag_path: 'MS.png',
    tel_code: '+1664',
  },
  MD: {
    code_2: 'MD',
    code_3: 'MDA',
    name: '몰도바',
    name_en: 'MOLDOVA, REPUBLIC OF',
    name_origin: 'Moldova',
    flag_path: 'MD.png',
    tel_code: '+373',
  },
  MV: {
    code_2: 'MV',
    code_3: 'MDV',
    name: '몰디브',
    name_en: 'MALDIVES',
    name_origin: 'ގުޖޭއްރާ ޔާއްރިހޫމްޖ',
    flag_path: 'MV.png',
    tel_code: '+960',
  },
  MT: {
    code_2: 'MT',
    code_3: 'MLT',
    name: '몰타',
    name_en: 'MALTA',
    name_origin: 'Malta',
    flag_path: 'MT.png',
    tel_code: '+356',
  },
  MN: {
    code_2: 'MN',
    code_3: 'MNG',
    name: '몽골',
    name_en: 'MONGOLIA',
    name_origin: 'Монгол Улс',
    flag_path: 'MN.png',
    tel_code: '+976',
  },
  US: {
    code_2: 'US',
    code_3: 'USA',
    name: '미국',
    name_en: 'UNITED STATES',
    name_origin: 'United States',
    flag_path: 'US.png',
    tel_code: '+1',
  },
  UM: {
    code_2: 'UM',
    code_3: 'UMI',
    name: '미국령 군소 제도',
    name_en: 'UNITED STATES MINOR OUTLYING ISLANDS',
    name_origin: 'United States minor outlying islands',
    flag_path: 'UM.png',
    tel_code: '+0',
  },
  VI: {
    code_2: 'VI',
    code_3: 'VIR',
    name: '미국령 버진아일랜드',
    name_en: 'VIRGIN ISLANDS, U.S.',
    name_origin: 'Virgin Islands, U.S.',
    flag_path: 'VI.png',
    tel_code: '+1340',
  },
  MM: {
    code_2: 'MM',
    code_3: 'MMR',
    name: '미얀마',
    name_en: 'MYANMAR',
    name_origin: 'Myanmar(Burma)',
    flag_path: 'MM.png',
    tel_code: '+95',
  },
  FM: {
    code_2: 'FM',
    code_3: 'FSM',
    name: '미크로네시아 연방',
    name_en: 'MICRONESIA',
    name_origin: 'Micronesia',
    flag_path: 'FM.png',
    tel_code: '+691',
  },
  VU: {
    code_2: 'VU',
    code_3: 'VUT',
    name: '바누아투',
    name_en: 'VANUATU',
    name_origin: 'Vanuatu',
    flag_path: 'VU.png',
    tel_code: '+678',
  },
  BH: {
    code_2: 'BH',
    code_3: 'BHR',
    name: '바레인',
    name_en: 'BAHRAIN',
    name_origin: 'البحرين',
    flag_path: 'BH.png',
    tel_code: '+973',
  },
  BB: {
    code_2: 'BB',
    code_3: 'BRB',
    name: '바베이도스',
    name_en: 'BARBADOS',
    name_origin: 'Barbados',
    flag_path: 'BB.png',
    tel_code: '+1246',
  },
  VA: {
    code_2: 'VA',
    code_3: 'VAT',
    name: '바티칸 시국',
    name_en: 'VATICAN CITY STATE',
    name_origin: 'Città del Vaticano',
    flag_path: 'VA.png',
    tel_code: '+379',
  },
  BS: {
    code_2: 'BS',
    code_3: 'BHS',
    name: '바하마',
    name_en: 'BAHAMAS',
    name_origin: 'Bahamas',
    flag_path: 'BS.png',
    tel_code: '+1242',
  },
  BD: {
    code_2: 'BD',
    code_3: 'BGD',
    name: '방글라데시',
    name_en: 'BANGLADESH',
    name_origin: 'বাংলাদেশ',
    flag_path: 'BD.png',
    tel_code: '+880',
  },
  BM: {
    code_2: 'BM',
    code_3: 'BMU',
    name: '버뮤다',
    name_en: 'BERMUDA',
    name_origin: 'Bermuda',
    flag_path: 'BM.png',
    tel_code: '+1441',
  },
  BJ: {
    code_2: 'BJ',
    code_3: 'BEN',
    name: '베냉',
    name_en: 'BENIN',
    name_origin: 'Bénin',
    flag_path: 'BJ.png',
    tel_code: '+229',
  },
  VE: {
    code_2: 'VE',
    code_3: 'VEN',
    name: '베네수엘라',
    name_en: 'VENEZUELA',
    name_origin: 'Venezuela',
    flag_path: 'VE.png',
    tel_code: '+58',
  },
  VN: {
    code_2: 'VN',
    code_3: 'VNM',
    name: '베트남',
    name_en: 'VIET NAM',
    name_origin: 'Việt Nam',
    flag_path: 'VN.png',
    tel_code: '+84',
  },
  BE: {
    code_2: 'BE',
    code_3: 'BEL',
    name: '벨기에',
    name_en: 'BELGIUM',
    name_origin: 'België',
    flag_path: 'BE.png',
    tel_code: '+32',
  },
  BY: {
    code_2: 'BY',
    code_3: 'BLR',
    name: '벨라루스',
    name_en: 'BELARUS',
    name_origin: 'Белару́сь',
    flag_path: 'BY.png',
    tel_code: '+375',
  },
  BZ: {
    code_2: 'BZ',
    code_3: 'BLZ',
    name: '벨리즈',
    name_en: 'BELIZE',
    name_origin: 'Belize',
    flag_path: 'BZ.png',
    tel_code: '+501',
  },
  BA: {
    code_2: 'BA',
    code_3: 'BIH',
    name: '보스니아 헤르체고비나',
    name_en: 'BOSNIA HERCEGOVINA',
    name_origin: 'Bosna i Hercegovina',
    flag_path: 'BA.png',
    tel_code: '+387',
  },
  BW: {
    code_2: 'BW',
    code_3: 'BWA',
    name: '보츠와나',
    name_en: 'BOTSWANA',
    name_origin: 'Botswana',
    flag_path: 'BW.png',
    tel_code: '+267',
  },
  BO: {
    code_2: 'BO',
    code_3: 'BOL',
    name: '볼리비아',
    name_en: 'BOLIVIA',
    name_origin: 'Bolivia',
    flag_path: 'BO.png',
    tel_code: '+591',
  },
  BI: {
    code_2: 'BI',
    code_3: 'BDI',
    name: '부룬디',
    name_en: 'BURUNDI',
    name_origin: 'Uburundi',
    flag_path: 'BI.png',
    tel_code: '+257',
  },
  BF: {
    code_2: 'BF',
    code_3: 'BFA',
    name: '부르키나파소',
    name_en: 'BURKINA FASO',
    name_origin: 'Burkina Faso',
    flag_path: 'BF.png',
    tel_code: '+226',
  },
  BV: {
    code_2: 'BV',
    code_3: 'BVT',
    name: '부베 섬',
    name_en: 'BOUVET ISLAND',
    name_origin: 'Bouvet Island',
    flag_path: 'BV.png',
    tel_code: '+47',
  },
  BT: {
    code_2: 'BT',
    code_3: 'BTN',
    name: '부탄',
    name_en: 'BHUTAN',
    name_origin: 'འབྲུག་ཡུལ',
    flag_path: 'BT.png',
    tel_code: '+975',
  },
  MP: {
    code_2: 'MP',
    code_3: 'MNP',
    name: '북마리아나 제도',
    name_en: 'NORTHERN MARIANA ISLANDS',
    name_origin: 'Northern Mariana Islands',
    flag_path: 'MP.png',
    tel_code: '+1670',
  },
  BG: {
    code_2: 'BG',
    code_3: 'BGR',
    name: '불가리아',
    name_en: 'BULGARIA',
    name_origin: 'България',
    flag_path: 'BG.png',
    tel_code: '+359',
  },
  BR: {
    code_2: 'BR',
    code_3: 'BRA',
    name: '브라질',
    name_en: 'BRAZIL',
    name_origin: 'Brasil',
    flag_path: 'BR.png',
    tel_code: '+55',
  },
  BN: {
    code_2: 'BN',
    code_3: 'BRN',
    name: '브루나이',
    name_en: 'BRUNEI DARUSSALAM',
    name_origin: 'Brunei Darussalam',
    flag_path: 'BN.png',
    tel_code: '+673',
  },
  WS: {
    code_2: 'WS',
    code_3: 'WSM',
    name: '사모아',
    name_en: 'SAMOA',
    name_origin: 'Samoa',
    flag_path: 'WS.png',
    tel_code: '+685',
  },
  SA: {
    code_2: 'SA',
    code_3: 'SAU',
    name: '사우디아라비아',
    name_en: 'SAUDI ARABIA',
    name_origin: 'المملكة العربية السعودية',
    flag_path: 'SA.png',
    tel_code: '+966',
  },
  GS: {
    code_2: 'GS',
    code_3: 'SGS',
    name: '사우스조지아 사우스샌드위치 제도',
    name_en: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    name_origin: 'South Georgia and the South Sandwich Islands',
    flag_path: 'GS.png',
    tel_code: '+44',
  },
  SM: {
    code_2: 'SM',
    code_3: 'SMR',
    name: '산마리노',
    name_en: 'SAN MARINO',
    name_origin: 'San Marino',
    flag_path: 'SM.png',
    tel_code: '+378',
  },
  ST: {
    code_2: 'ST',
    code_3: 'STP',
    name: '상투메 프린시페',
    name_en: 'SAO TOME AND PRINCIPE',
    name_origin: 'São Tomé and Príncipe',
    flag_path: 'ST.png',
    tel_code: '+239',
  },
  PM: {
    code_2: 'PM',
    code_3: 'SPM',
    name: '생피에르 미클롱',
    name_en: 'ST. PIERRE AND MIQUELON',
    name_origin: 'Saint Pierre and Miquelon',
    flag_path: 'PM.png',
    tel_code: '+508',
  },
  EH: {
    code_2: 'EH',
    code_3: 'ESH',
    name: '서사하라',
    name_en: 'WESTERN SAHARA',
    name_origin: 'الصحراء الغربية',
    flag_path: 'EH.png',
    tel_code: '+212',
  },
  SN: {
    code_2: 'SN',
    code_3: 'SEN',
    name: '세네갈',
    name_en: 'SENEGAL',
    name_origin: 'Sénégal',
    flag_path: 'SN.png',
    tel_code: '+221',
  },
  RS: {
    code_2: 'RS',
    code_3: 'SRB',
    name: '세르비아',
    name_en: 'SERBIA',
    name_origin: 'Србија',
    flag_path: 'RS.png',
    tel_code: '+381',
  },
  SC: {
    code_2: 'SC',
    code_3: 'SYC',
    name: '세이셸',
    name_en: 'SEYCHELLES',
    name_origin: 'Seychelles',
    flag_path: 'SC.png',
    tel_code: '+248',
  },
  LC: {
    code_2: 'LC',
    code_3: 'LCA',
    name: '세인트루시아',
    name_en: 'SAINT LUCIA',
    name_origin: 'Saint Lucia',
    flag_path: 'LC.png',
    tel_code: '+1758',
  },
  VC: {
    code_2: 'VC',
    code_3: 'VCT',
    name: '세인트빈센트 그레나딘',
    name_en: 'SAINT VINCENT AND THE GRENADINES',
    name_origin: 'Saint Vincent and the Grenadines',
    flag_path: 'VC.png',
    tel_code: '+1784',
  },
  KN: {
    code_2: 'KN',
    code_3: 'KNA',
    name: '세인트키츠 네비스',
    name_en: 'SAINT KITTS AND NEVIS',
    name_origin: 'Saint Kitts and Nevis',
    flag_path: 'KN.png',
    tel_code: '+1869',
  },
  SH: {
    code_2: 'SH',
    code_3: 'SHN',
    name: '세인트헬레나',
    name_en: 'ST. HELENA',
    name_origin: 'Saint Helena',
    flag_path: 'SH.png',
    tel_code: '+290',
  },
  SO: {
    code_2: 'SO',
    code_3: 'SOM',
    name: '소말리아',
    name_en: 'SOMALIA',
    name_origin: 'Soomaaliya',
    flag_path: 'SO.png',
    tel_code: '+252',
  },
  SB: {
    code_2: 'SB',
    code_3: 'SLB',
    name: '솔로몬 제도',
    name_en: 'SOLOMON ISLANDS',
    name_origin: 'Solomon Islands',
    flag_path: 'SB.png',
    tel_code: '+677',
  },
  SD: {
    code_2: 'SD',
    code_3: 'SDN',
    name: '수단',
    name_en: 'SUDAN',
    name_origin: 'السودان',
    flag_path: 'SD.png',
    tel_code: '+249',
  },
  SR: {
    code_2: 'SR',
    code_3: 'SUR',
    name: '수리남',
    name_en: 'SURINAME',
    name_origin: 'Suriname',
    flag_path: 'SR.png',
    tel_code: '+597',
  },
  LK: {
    code_2: 'LK',
    code_3: 'LKA',
    name: '스리랑카',
    name_en: 'SRI LANKA',
    name_origin: 'Sri Lanka',
    flag_path: 'LK.png',
    tel_code: '+94',
  },
  SJ: {
    code_2: 'SJ',
    code_3: 'SJM',
    name: '스발바르 얀마옌',
    name_en: 'SVALBARD AND JAN MAYEN ISLANDS',
    name_origin: 'Svalbard and Jan Mayen',
    flag_path: 'SJ.png',
    tel_code: '+47',
  },
  SZ: {
    code_2: 'SZ',
    code_3: 'SWZ',
    name: '스와질란드',
    name_en: 'SWAZILAND',
    name_origin: 'Swaziland',
    flag_path: 'SZ.png',
    tel_code: '+268',
  },
  SE: {
    code_2: 'SE',
    code_3: 'SWE',
    name: '스웨덴',
    name_en: 'SWEDEN',
    name_origin: 'Sverige',
    flag_path: 'SE.png',
    tel_code: '+46',
  },
  CH: {
    code_2: 'CH',
    code_3: 'CHE',
    name: '스위스',
    name_en: 'SWITZERLAND',
    name_origin: 'Schweiz',
    flag_path: 'CH.png',
    tel_code: '+41',
  },
  ES: {
    code_2: 'ES',
    code_3: 'ESP',
    name: '스페인',
    name_en: 'SPAIN',
    name_origin: 'España',
    flag_path: 'ES.png',
    tel_code: '+34',
  },
  SK: {
    code_2: 'SK',
    code_3: 'SVK',
    name: '슬로바키아',
    name_en: 'SLOVAKIA',
    name_origin: 'Slovensko',
    flag_path: 'SK.png',
    tel_code: '+421',
  },
  SI: {
    code_2: 'SI',
    code_3: 'SVN',
    name: '슬로베니아',
    name_en: 'SLOVENIA',
    name_origin: 'Slovenija',
    flag_path: 'SI.png',
    tel_code: '+386',
  },
  SY: {
    code_2: 'SY',
    code_3: 'SYR',
    name: '시리아',
    name_en: 'SYRIAN ARAB REPUBLIC',
    name_origin: 'سوريا',
    flag_path: 'SY.png',
    tel_code: '+963',
  },
  SL: {
    code_2: 'SL',
    code_3: 'SLE',
    name: '시에라리온',
    name_en: 'SIERRA LEONE',
    name_origin: 'Sierra Leone',
    flag_path: 'SL.png',
    tel_code: '+232',
  },
  SX: {
    code_2: 'SX',
    code_3: 'SXM',
    name: '신트마르턴',
    name_en: 'Sint Maarten',
    name_origin: 'Eilandgebied Sint Maarten',
    flag_path: 'SX.png',
    tel_code: '+1721',
  },
  SG: {
    code_2: 'SG',
    code_3: 'SGP',
    name: '싱가포르',
    name_en: 'SINGAPORE',
    name_origin: 'Singapura',
    flag_path: 'SG.png',
    tel_code: '+65',
  },
  AE: {
    code_2: 'AE',
    code_3: 'ARE',
    name: '아랍에미리트',
    name_en: 'UNITED ARAB EMIRATES',
    name_origin: 'الإمارات العربيّة المتّحدة',
    flag_path: 'AE.png',
    tel_code: '+971',
  },
  AW: {
    code_2: 'AW',
    code_3: 'ABW',
    name: '아루바',
    name_en: 'ARUBA',
    name_origin: 'Aruba',
    flag_path: 'AW.png',
    tel_code: '+297',
  },
  AM: {
    code_2: 'AM',
    code_3: 'ARM',
    name: '아르메니아',
    name_en: 'ARMENIA',
    name_origin: 'Հայաստան',
    flag_path: 'AM.png',
    tel_code: '+374',
  },
  AR: {
    code_2: 'AR',
    code_3: 'ARG',
    name: '아르헨티나',
    name_en: 'ARGENTINA',
    name_origin: 'Argentina',
    flag_path: 'AR.png',
    tel_code: '+54',
  },
  AS: {
    code_2: 'AS',
    code_3: 'ASM',
    name: '아메리칸사모아',
    name_en: 'AMERICAN SAMOA',
    name_origin: 'American Samoa',
    flag_path: 'AS.png',
    tel_code: '+1684',
  },
  IS: {
    code_2: 'IS',
    code_3: 'ISL',
    name: '아이슬란드',
    name_en: 'ICELAND',
    name_origin: 'Ísland',
    flag_path: 'IS.png',
    tel_code: '+354',
  },
  HT: {
    code_2: 'HT',
    code_3: 'HTI',
    name: '아이티',
    name_en: 'HAITI',
    name_origin: 'Haïti',
    flag_path: 'HT.png',
    tel_code: '+509',
  },
  IE: {
    code_2: 'IE',
    code_3: 'IRL',
    name: '아일랜드',
    name_en: 'IRELAND',
    name_origin: 'Ireland',
    flag_path: 'IE.png',
    tel_code: '+353',
  },
  AZ: {
    code_2: 'AZ',
    code_3: 'AZE',
    name: '아제르바이잔',
    name_en: 'AZERBAIJAN',
    name_origin: 'Azərbaycan',
    flag_path: 'AZ.png',
    tel_code: '+994',
  },
  AF: {
    code_2: 'AF',
    code_3: 'AFG',
    name: '아프가니스탄',
    name_en: 'AFGHANISTAN',
    name_origin: 'افغانستان',
    flag_path: 'AF.png',
    tel_code: '+93',
  },
  AD: {
    code_2: 'AD',
    code_3: 'AND',
    name: '안도라',
    name_en: 'ANDORRA',
    name_origin: 'Andorra',
    flag_path: 'AD.png',
    tel_code: '+376',
  },
  AL: {
    code_2: 'AL',
    code_3: 'ALB',
    name: '알바니아',
    name_en: 'ALBANIA',
    name_origin: 'Shqipëria',
    flag_path: 'AL.png',
    tel_code: '+355',
  },
  DZ: {
    code_2: 'DZ',
    code_3: 'DZA',
    name: '알제리',
    name_en: 'ALGERIA',
    name_origin: 'الجزائر',
    flag_path: 'DZ.png',
    tel_code: '+213',
  },
  AO: {
    code_2: 'AO',
    code_3: 'AGO',
    name: '앙골라',
    name_en: 'ANGOLA',
    name_origin: 'Angola',
    flag_path: 'AO.png',
    tel_code: '+244',
  },
  AG: {
    code_2: 'AG',
    code_3: 'ATG',
    name: '앤티가 바부다',
    name_en: 'ANTIGUA AND BARBUDA',
    name_origin: 'Antigua and Barbuda',
    flag_path: 'AG.png',
    tel_code: '+1268',
  },
  AI: {
    code_2: 'AI',
    code_3: 'AIA',
    name: '앵귈라',
    name_en: 'ANGUILLA',
    name_origin: 'Anguilla',
    flag_path: 'AI.png',
    tel_code: '+1264',
  },
  ER: {
    code_2: 'ER',
    code_3: 'ERI',
    name: '에리트레아',
    name_en: 'ERITREA',
    name_origin: 'Ertra',
    flag_path: 'ER.png',
    tel_code: '+291',
  },
  EE: {
    code_2: 'EE',
    code_3: 'EST',
    name: '에스토니아',
    name_en: 'ESTONIA',
    name_origin: 'Eesti',
    flag_path: 'EE.png',
    tel_code: '+372',
  },
  EC: {
    code_2: 'EC',
    code_3: 'ECU',
    name: '에콰도르',
    name_en: 'ECUADOR',
    name_origin: 'Ecuador',
    flag_path: 'EC.png',
    tel_code: '+593',
  },
  ET: {
    code_2: 'ET',
    code_3: 'ETH',
    name: '에티오피아',
    name_en: 'ETHIOPIA',
    name_origin: "Ityop'iya",
    flag_path: 'ET.png',
    tel_code: '+251',
  },
  SV: {
    code_2: 'SV',
    code_3: 'SLV',
    name: '엘살바도르',
    name_en: 'EL SALVADOR',
    name_origin: 'El Salvador',
    flag_path: 'SV.png',
    tel_code: '+503',
  },
  GB: {
    code_2: 'GB',
    code_3: 'GBR',
    name: '영국',
    name_en: 'UNITED KINGDOM',
    name_origin: 'United Kingdom',
    flag_path: 'GB.png',
    tel_code: '+44',
  },
  VG: {
    code_2: 'VG',
    code_3: 'VGB',
    name: '영국령 버진아일랜드',
    name_en: 'VIRGIN ISLANDS, BRITISH',
    name_origin: 'Virgin Islands, British',
    flag_path: 'VG.png',
    tel_code: '+1284',
  },
  IO: {
    code_2: 'IO',
    code_3: 'IOT',
    name: '영국령 인도양 지역',
    name_en: 'BRITISH INDIAN OCEAN TERRITORY',
    name_origin: 'British Indian Ocean Territory',
    flag_path: 'IO.png',
    tel_code: '+246',
  },
  YE: {
    code_2: 'YE',
    code_3: 'YEM',
    name: '예멘',
    name_en: 'YEMEN, REPUBLIC OF',
    name_origin: 'اليمن',
    flag_path: 'YE.png',
    tel_code: '+967',
  },
  OM: {
    code_2: 'OM',
    code_3: 'OMN',
    name: '오만',
    name_en: 'OMAN',
    name_origin: 'عمان',
    flag_path: 'OM.png',
    tel_code: '+968',
  },
  AU: {
    code_2: 'AU',
    code_3: 'AUS',
    name: '오스트레일리아',
    name_en: 'AUSTRALIA',
    name_origin: 'Australia',
    flag_path: 'AU.png',
    tel_code: '+61',
  },
  AT: {
    code_2: 'AT',
    code_3: 'AUT',
    name: '오스트리아',
    name_en: 'AUSTRIA',
    name_origin: 'Österreich',
    flag_path: 'AT.png',
    tel_code: '+43',
  },
  HN: {
    code_2: 'HN',
    code_3: 'HND',
    name: '온두라스',
    name_en: 'HONDURAS',
    name_origin: 'Honduras',
    flag_path: 'HN.png',
    tel_code: '+504',
  },
  AX: {
    code_2: 'AX',
    code_3: 'ALA',
    name: '올란드 제도',
    name_en: 'ALAND ISLANDS',
    name_origin: 'Aland Islands',
    flag_path: 'AX.png',
    tel_code: '+35818',
  },
  WF: {
    code_2: 'WF',
    code_3: 'WLF',
    name: '왈리스 퓌튀나',
    name_en: 'WALLIS AND FUTUNA ISLANDS',
    name_origin: 'Wallis and Futuna',
    flag_path: 'WF.png',
    tel_code: '+681',
  },
  JO: {
    code_2: 'JO',
    code_3: 'JOR',
    name: '요르단',
    name_en: 'JORDAN',
    name_origin: 'الاردن',
    flag_path: 'JO.png',
    tel_code: '+962',
  },
  UG: {
    code_2: 'UG',
    code_3: 'UGA',
    name: '우간다',
    name_en: 'UGANDA',
    name_origin: 'Uganda',
    flag_path: 'UG.png',
    tel_code: '+256',
  },
  UY: {
    code_2: 'UY',
    code_3: 'URY',
    name: '우루과이',
    name_en: 'URUGUAY',
    name_origin: 'Uruguay',
    flag_path: 'UY.png',
    tel_code: '+598',
  },
  UZ: {
    code_2: 'UZ',
    code_3: 'UZB',
    name: '우즈베키스탄',
    name_en: 'UZBEKISTAN',
    name_origin: "O'zbekiston",
    flag_path: 'UZ.png',
    tel_code: '+998',
  },
  UA: {
    code_2: 'UA',
    code_3: 'UKR',
    name: '우크라이나',
    name_en: 'UKRAINE',
    name_origin: 'Україна',
    flag_path: 'UA.png',
    tel_code: '+380',
  },
  IQ: {
    code_2: 'IQ',
    code_3: 'IRQ',
    name: '이라크',
    name_en: 'IRAQ',
    name_origin: 'العراق',
    flag_path: 'IQ.png',
    tel_code: '+98',
  },
  IR: {
    code_2: 'IR',
    code_3: 'IRN',
    name: '이란',
    name_en: 'IRAN',
    name_origin: 'ایران',
    flag_path: 'IR.png',
    tel_code: '+964',
  },
  IL: {
    code_2: 'IL',
    code_3: 'ISR',
    name: '이스라엘',
    name_en: 'ISRAEL',
    name_origin: 'ישראל',
    flag_path: 'IL.png',
    tel_code: '+972',
  },
  EG: {
    code_2: 'EG',
    code_3: 'EGY',
    name: '이집트',
    name_en: 'EGYPT',
    name_origin: 'مصر',
    flag_path: 'EG.png',
    tel_code: '+20',
  },
  IT: {
    code_2: 'IT',
    code_3: 'ITA',
    name: '이탈리아',
    name_en: 'ITALY',
    name_origin: 'Italia',
    flag_path: 'IT.png',
    tel_code: '+39',
  },
  IN: {
    code_2: 'IN',
    code_3: 'IND',
    name: '인도',
    name_en: 'INDIA',
    name_origin: 'India',
    flag_path: 'IN.png',
    tel_code: '+91',
  },
  ID: {
    code_2: 'ID',
    code_3: 'IDN',
    name: '인도네시아',
    name_en: 'INDONESIA',
    name_origin: 'Indonesia',
    flag_path: 'ID.png',
    tel_code: '+62',
  },
  JP: {
    code_2: 'JP',
    code_3: 'JPN',
    name: '일본',
    name_en: 'JAPAN',
    name_origin: '日本',
    flag_path: 'JP.png',
    tel_code: '+81',
  },
  JM: {
    code_2: 'JM',
    code_3: 'JAM',
    name: '자메이카',
    name_en: 'JAMAICA',
    name_origin: 'Jamaica',
    flag_path: 'JM.png',
    tel_code: '+1876',
  },
  ZM: {
    code_2: 'ZM',
    code_3: 'ZMB',
    name: '잠비아',
    name_en: 'ZAMBIA',
    name_origin: 'Zambia',
    flag_path: 'ZM.png',
    tel_code: '+260',
  },
  JE: {
    code_2: 'JE',
    code_3: 'JEY',
    name: '저지 섬',
    name_en: 'JERSEY',
    name_origin: 'Jersey',
    flag_path: 'JE.png',
    tel_code: '+441534',
  },
  GQ: {
    code_2: 'GQ',
    code_3: 'GNQ',
    name: '적도 기니',
    name_en: 'EQUATORIAL GUINEA',
    name_origin: 'Guinea Ecuatorial',
    flag_path: 'GQ.png',
    tel_code: '+240',
  },
  KP: {
    code_2: 'KP',
    code_3: 'PRK',
    name: '조선민주주의인민공화국',
    name_en: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    name_origin: '조선',
    flag_path: 'KP.png',
    tel_code: '+850',
  },
  GE: {
    code_2: 'GE',
    code_3: 'GEO',
    name: '조지아',
    name_en: 'GEORGIA',
    name_origin: 'საქართველო',
    flag_path: 'GE.png',
    tel_code: '+995',
  },
  CF: {
    code_2: 'CF',
    code_3: 'CAF',
    name: '중앙아프리카 공화국',
    name_en: 'CENTRAL AFRICAN REPUBLIC',
    name_origin: 'République Centrafricaine',
    flag_path: 'CF.png',
    tel_code: '+236',
  },
  TW: {
    code_2: 'TW',
    code_3: 'TWN',
    name: '중화민국',
    name_en: 'TAIWAN, PROVINCE OF CHINA',
    name_origin: '台灣',
    flag_path: 'TW.png',
    tel_code: '+886',
  },
  CN: {
    code_2: 'CN',
    code_3: 'CHN',
    name: '중화인민공화국',
    name_en: 'CHINA',
    name_origin: '中国',
    flag_path: 'CN.png',
    tel_code: '+86',
  },
  DJ: {
    code_2: 'DJ',
    code_3: 'DJI',
    name: '지부티',
    name_en: 'DJIBOUTI',
    name_origin: 'Djibouti',
    flag_path: 'DJ.png',
    tel_code: '+253',
  },
  GI: {
    code_2: 'GI',
    code_3: 'GIB',
    name: '지브롤터',
    name_en: 'GIBRALTAR',
    name_origin: 'Gibraltar',
    flag_path: 'GI.png',
    tel_code: '+350',
  },
  ZW: {
    code_2: 'ZW',
    code_3: 'ZWE',
    name: '짐바브웨',
    name_en: 'ZIMBABWE',
    name_origin: 'Zimbabwe',
    flag_path: 'ZW.png',
    tel_code: '+263',
  },
  TD: {
    code_2: 'TD',
    code_3: 'TCD',
    name: '차드',
    name_en: 'CHAD',
    name_origin: 'Tchad',
    flag_path: 'TD.png',
    tel_code: '+235',
  },
  CZ: {
    code_2: 'CZ',
    code_3: 'CZE',
    name: '체코',
    name_en: 'CZECH REPUBLIC',
    name_origin: 'Česko',
    flag_path: 'CZ.png',
    tel_code: '+420',
  },
  CL: {
    code_2: 'CL',
    code_3: 'CHL',
    name: '칠레',
    name_en: 'CHILE',
    name_origin: 'Chile',
    flag_path: 'CL.png',
    tel_code: '+56',
  },
  CM: {
    code_2: 'CM',
    code_3: 'CMR',
    name: '카메룬',
    name_en: 'CAMEROON',
    name_origin: 'Cameroun',
    flag_path: 'CM.png',
    tel_code: '+237',
  },
  CV: {
    code_2: 'CV',
    code_3: 'CPV',
    name: '카보베르데',
    name_en: 'CAPE VERDE',
    name_origin: 'Cabo Verde',
    flag_path: 'CV.png',
    tel_code: '+238',
  },
  KZ: {
    code_2: 'KZ',
    code_3: 'KAZ',
    name: '카자흐스탄',
    name_en: 'KAZAKHSTAN',
    name_origin: 'Қазақстан',
    flag_path: 'KZ.png',
    tel_code: '+7',
  },
  QA: {
    code_2: 'QA',
    code_3: 'QAT',
    name: '카타르',
    name_en: 'QATAR',
    name_origin: 'قطر',
    flag_path: 'QA.png',
    tel_code: '+974',
  },
  KH: {
    code_2: 'KH',
    code_3: 'KHM',
    name: '캄보디아',
    name_en: 'CAMBODIA',
    name_origin: 'Kampuchea',
    flag_path: 'KH.png',
    tel_code: '+855',
  },
  CA: {
    code_2: 'CA',
    code_3: 'CAN',
    name: '캐나다',
    name_en: 'CANADA',
    name_origin: 'Canada',
    flag_path: 'CA.png',
    tel_code: '+1',
  },
  KE: {
    code_2: 'KE',
    code_3: 'KEN',
    name: '케냐',
    name_en: 'KENYA',
    name_origin: 'Kenya',
    flag_path: 'KE.png',
    tel_code: '+254',
  },
  KY: {
    code_2: 'KY',
    code_3: 'CYM',
    name: '케이맨 제도',
    name_en: 'CAYMAN ISLANDS',
    name_origin: 'Cayman Islands',
    flag_path: 'KY.png',
    tel_code: '+1345',
  },
  KM: {
    code_2: 'KM',
    code_3: 'COM',
    name: '코모로',
    name_en: 'COMOROS',
    name_origin: 'Comores',
    flag_path: 'KM.png',
    tel_code: '+269',
  },
  CR: {
    code_2: 'CR',
    code_3: 'CRI',
    name: '코스타리카',
    name_en: 'COSTA RICA',
    name_origin: 'Costa Rica',
    flag_path: 'CR.png',
    tel_code: '+506',
  },
  CC: {
    code_2: 'CC',
    code_3: 'CCK',
    name: '코코스 제도',
    name_en: 'COCOS ISLANDS',
    name_origin: 'Cocos Islands',
    flag_path: 'CC.png',
    tel_code: '+6189162',
  },
  CI: {
    code_2: 'CI',
    code_3: 'CIV',
    name: '코트디부아르',
    name_en: "COTE D'IVOIRE",
    name_origin: "Côte d'Ivoire",
    flag_path: 'CI.png',
    tel_code: '+225',
  },
  CO: {
    code_2: 'CO',
    code_3: 'COL',
    name: '콜롬비아',
    name_en: 'COLOMBIA',
    name_origin: 'Colombia',
    flag_path: 'CO.png',
    tel_code: '+57',
  },
  CG: {
    code_2: 'CG',
    code_3: 'COG',
    name: '콩고 공화국',
    name_en: 'CONGO',
    name_origin: 'Congo',
    flag_path: 'CG.png',
    tel_code: '+242',
  },
  CD: {
    code_2: 'CD',
    code_3: 'COD',
    name: '콩고 민주 공화국',
    name_en: 'DEMOCRATIC REPUBLIC OF THE CONGO',
    name_origin: 'Congo, Democratic Republic of the',
    flag_path: 'CD.png',
    tel_code: '+243',
  },
  CU: {
    code_2: 'CU',
    code_3: 'CUB',
    name: '쿠바',
    name_en: 'CUBA',
    name_origin: 'Cuba',
    flag_path: 'CU.png',
    tel_code: '+53',
  },
  KW: {
    code_2: 'KW',
    code_3: 'KWT',
    name: '쿠웨이트',
    name_en: 'KUWAIT',
    name_origin: 'الكويت',
    flag_path: 'KW.png',
    tel_code: '+965',
  },
  CK: {
    code_2: 'CK',
    code_3: 'COK',
    name: '쿡 제도',
    name_en: 'COOK ISLANDS',
    name_origin: 'Cook Islands',
    flag_path: 'CK.png',
    tel_code: '+682',
  },
  HR: {
    code_2: 'HR',
    code_3: 'HRV',
    name: '크로아티아',
    name_en: 'CROATIA',
    name_origin: 'Hrvatska',
    flag_path: 'HR.png',
    tel_code: '+385',
  },
  CX: {
    code_2: 'CX',
    code_3: 'CXR',
    name: '크리스마스 섬',
    name_en: 'CHRISTMAS ISLAND',
    name_origin: 'Christmas Island',
    flag_path: 'CX.png',
    tel_code: '+6189164',
  },
  KG: {
    code_2: 'KG',
    code_3: 'KGZ',
    name: '키르기스스탄',
    name_en: 'KYRGYZSTAN',
    name_origin: 'Кыргызстан',
    flag_path: 'KG.png',
    tel_code: '+996',
  },
  KI: {
    code_2: 'KI',
    code_3: 'KIR',
    name: '키리바시',
    name_en: 'KIRIBATI',
    name_origin: 'Kiribati',
    flag_path: 'KI.png',
    tel_code: '+686',
  },
  CY: {
    code_2: 'CY',
    code_3: 'CYP',
    name: '키프로스',
    name_en: 'CYPRUS',
    name_origin: 'Κυπρος',
    flag_path: 'CY.png',
    tel_code: '+357',
  },
  TH: {
    code_2: 'TH',
    code_3: 'THA',
    name: '타이',
    name_en: 'THAILAND',
    name_origin: 'ราชอาณาจักรไทย',
    flag_path: 'TH.png',
    tel_code: '+66',
  },
  TJ: {
    code_2: 'TJ',
    code_3: 'TJK',
    name: '타지키스탄',
    name_en: 'TAJIKISTAN',
    name_origin: 'Тоҷикистон',
    flag_path: 'TJ.png',
    tel_code: '+992',
  },
  TZ: {
    code_2: 'TZ',
    code_3: 'TZA',
    name: '탄자니아',
    name_en: 'TANZANIA, UNITED REPUBLIC OF',
    name_origin: 'Tanzania',
    flag_path: 'TZ.png',
    tel_code: '+255',
  },
  TC: {
    code_2: 'TC',
    code_3: 'TCA',
    name: '터크스 케이커스 제도',
    name_en: 'TURKS AND CAICOS ISLANDS',
    name_origin: 'Turks and Caicos Islands',
    flag_path: 'TC.png',
    tel_code: '+1649',
  },
  TR: {
    code_2: 'TR',
    code_3: 'TUR',
    name: '터키',
    name_en: 'TURKEY',
    name_origin: 'Türkiye',
    flag_path: 'TR.png',
    tel_code: '+90',
  },
  TG: {
    code_2: 'TG',
    code_3: 'TGO',
    name: '토고',
    name_en: 'TOGO',
    name_origin: 'Togo',
    flag_path: 'TG.png',
    tel_code: '+228',
  },
  TK: {
    code_2: 'TK',
    code_3: 'TKL',
    name: '토켈라우',
    name_en: 'TOKELAU',
    name_origin: 'Tokelau',
    flag_path: 'TK.png',
    tel_code: '+690',
  },
  TO: {
    code_2: 'TO',
    code_3: 'TON',
    name: '통가',
    name_en: 'TONGA',
    name_origin: 'Tonga',
    flag_path: 'TO.png',
    tel_code: '+676',
  },
  TM: {
    code_2: 'TM',
    code_3: 'TKM',
    name: '투르크메니스탄',
    name_en: 'TURKMENISTAN',
    name_origin: 'Türkmenistan',
    flag_path: 'TM.png',
    tel_code: '+993',
  },
  TV: {
    code_2: 'TV',
    code_3: 'TUV',
    name: '투발루',
    name_en: 'TUVALU',
    name_origin: 'Tuvalu',
    flag_path: 'TV.png',
    tel_code: '+688',
  },
  TN: {
    code_2: 'TN',
    code_3: 'TUN',
    name: '튀니지',
    name_en: 'TUNISIA',
    name_origin: 'تونس',
    flag_path: 'TN.png',
    tel_code: '+216',
  },
  TT: {
    code_2: 'TT',
    code_3: 'TTO',
    name: '트리니다드 토바고',
    name_en: 'TRINIDAD AND TOBAGO',
    name_origin: 'Trinidad and Tobago',
    flag_path: 'TT.png',
    tel_code: '+1868',
  },
  PA: {
    code_2: 'PA',
    code_3: 'PAN',
    name: '파나마',
    name_en: 'PANAMA',
    name_origin: 'Panamá',
    flag_path: 'PA.png',
    tel_code: '+507',
  },
  PY: {
    code_2: 'PY',
    code_3: 'PRY',
    name: '파라과이',
    name_en: 'PARAGUAY',
    name_origin: 'Paraguay',
    flag_path: 'PY.png',
    tel_code: '+595',
  },
  PK: {
    code_2: 'PK',
    code_3: 'PAK',
    name: '파키스탄',
    name_en: 'PAKISTAN',
    name_origin: 'پاکستان',
    flag_path: 'PK.png',
    tel_code: '+92',
  },
  PG: {
    code_2: 'PG',
    code_3: 'PNG',
    name: '파푸아 뉴기니',
    name_en: 'PAPUA NEW GUINEA',
    name_origin: 'Papua New Guinea',
    flag_path: 'PG.png',
    tel_code: '+675',
  },
  PW: {
    code_2: 'PW',
    code_3: 'PLW',
    name: '팔라우',
    name_en: 'PALAU',
    name_origin: 'Belau',
    flag_path: 'PW.png',
    tel_code: '+680',
  },
  PS: {
    code_2: 'PS',
    code_3: 'PSE',
    name: '팔레스타인',
    name_en: 'PALESTINE',
    name_origin: 'Palestinian Territories',
    flag_path: 'PS.png',
    tel_code: '+970',
  },
  FO: {
    code_2: 'FO',
    code_3: 'FRO',
    name: '페로 제도',
    name_en: 'FAROE ISLANDS',
    name_origin: 'Faroe Islands',
    flag_path: 'FO.png',
    tel_code: '+298',
  },
  PE: {
    code_2: 'PE',
    code_3: 'PER',
    name: '페루',
    name_en: 'PERU',
    name_origin: 'Perú',
    flag_path: 'PE.png',
    tel_code: '+51',
  },
  PT: {
    code_2: 'PT',
    code_3: 'PRT',
    name: '포르투갈',
    name_en: 'PORTUGAL',
    name_origin: 'Portugal',
    flag_path: 'PT.png',
    tel_code: '+351',
  },
  FK: {
    code_2: 'FK',
    code_3: 'FLK',
    name: '포클랜드 제도',
    name_en: 'FALKLAND ISLANDS',
    name_origin: 'Falkland Islands',
    flag_path: 'FK.png',
    tel_code: '+500',
  },
  PL: {
    code_2: 'PL',
    code_3: 'POL',
    name: '폴란드',
    name_en: 'POLAND',
    name_origin: 'Polska',
    flag_path: 'PL.png',
    tel_code: '+48',
  },
  PR: {
    code_2: 'PR',
    code_3: 'PRI',
    name: '푸에르토리코',
    name_en: 'PUERTO RICO',
    name_origin: 'Puerto Rico',
    flag_path: 'PR.png',
    tel_code: '+1787',
  },
  FR: {
    code_2: 'FR',
    code_3: 'FRA',
    name: '프랑스',
    name_en: 'FRANCE',
    name_origin: 'France',
    flag_path: 'FR.png',
    tel_code: '+33',
  },
  GF: {
    code_2: 'GF',
    code_3: 'GUF',
    name: '프랑스령 기아나',
    name_en: 'FRENCH GUIANA',
    name_origin: 'French Guiana',
    flag_path: 'GF.png',
    tel_code: '+594',
  },
  TF: {
    code_2: 'TF',
    code_3: 'ATF',
    name: '프랑스령 남부와 남극 지역',
    name_en: 'FRENCH SOUTHERN TERRITORIES',
    name_origin: 'French Southern Territories',
    flag_path: 'TF.png',
    tel_code: '+33',
  },
  PF: {
    code_2: 'PF',
    code_3: 'PYF',
    name: '프랑스령 폴리네시아',
    name_en: 'FRENCH POLYNESIA',
    name_origin: 'French Polynesia',
    flag_path: 'PF.png',
    tel_code: '+689',
  },

  가나: {
    code_2: 'GH',
    code_3: 'GHA',
    name: '가나',
    name_en: 'GHANA',
    name_origin: 'Ghana',
    flag_path: 'gh.png',
    tel_code: '+233',
  },
  가봉: {
    code_2: 'GA',
    code_3: 'GAB',
    name: '가봉',
    name_en: 'GABON',
    name_origin: 'Gabon',
    flag_path: 'ga.png',
    tel_code: '+241',
  },
  가이아나: {
    code_2: 'GY',
    code_3: 'GUY',
    name: '가이아나',
    name_en: 'GUYANA',
    name_origin: 'Guyana',
    flag_path: 'gy.png',
    tel_code: '+592',
  },
  감비아: {
    code_2: 'GM',
    code_3: 'GMB',
    name: '감비아',
    name_en: 'GAMBIA',
    name_origin: 'Gambia',
    flag_path: 'gm.png',
    tel_code: '+220',
  },
  '건지 섬': {
    code_2: 'GG',
    code_3: 'GGY',
    name: '건지 섬',
    name_en: 'GUERNSEY',
    name_origin: 'Guernsey',
    flag_path: 'GG.png',
    tel_code: '+441481',
  },
  과들루프: {
    code_2: 'GP',
    code_3: 'GLP',
    name: '과들루프',
    name_en: 'GUADELOUPE',
    name_origin: 'Guadeloupe',
    flag_path: 'GP.png',
    tel_code: '+590',
  },
  과테말라: {
    code_2: 'GT',
    code_3: 'GTM',
    name: '과테말라',
    name_en: 'GUATEMALA',
    name_origin: 'Guatemala',
    flag_path: 'GT.png',
    tel_code: '+502',
  },
  괌: {
    code_2: 'GU',
    code_3: 'GUM',
    name: '괌',
    name_en: 'GUAM',
    name_origin: 'Guam',
    flag_path: 'GU.png',
    tel_code: '+1671',
  },
  그레나다: {
    code_2: 'GD',
    code_3: 'GRD',
    name: '그레나다',
    name_en: 'GRENADA',
    name_origin: 'Grenada',
    flag_path: 'GD.png',
    tel_code: '+1473',
  },
  그리스: {
    code_2: 'GR',
    code_3: 'GRC',
    name: '그리스',
    name_en: 'GREECE',
    name_origin: 'Ελλάς',
    flag_path: 'GR.png',
    tel_code: '+30',
  },
  그린란드: {
    code_2: 'GL',
    code_3: 'GRL',
    name: '그린란드',
    name_en: 'GREENLAND',
    name_origin: 'Greenland',
    flag_path: 'GL.png',
    tel_code: '+299',
  },
  기니: {
    code_2: 'GN',
    code_3: 'GIN',
    name: '기니',
    name_en: 'GUINEA',
    name_origin: 'Guinée',
    flag_path: 'GN.png',
    tel_code: '+224',
  },
  기니비사우: {
    code_2: 'GW',
    code_3: 'GNB',
    name: '기니비사우',
    name_en: 'GUINEA-BISSAU',
    name_origin: 'Guiné-Bissau',
    flag_path: 'GW.png',
    tel_code: '+245',
  },
  나미비아: {
    code_2: 'NA',
    code_3: 'NAM',
    name: '나미비아',
    name_en: 'NAMIBIA',
    name_origin: 'Namibia',
    flag_path: 'NA.png',
    tel_code: '+264',
  },
  나우루: {
    code_2: 'NR',
    code_3: 'NRU',
    name: '나우루',
    name_en: 'NAURU',
    name_origin: 'Naoero',
    flag_path: 'NR.png',
    tel_code: '+674',
  },
  나이지리아: {
    code_2: 'NG',
    code_3: 'NGA',
    name: '나이지리아',
    name_en: 'NIGERIA',
    name_origin: 'Nigeria',
    flag_path: 'NG.png',
    tel_code: '+234',
  },
  남극: {
    code_2: 'AQ',
    code_3: 'ATA',
    name: '남극',
    name_en: 'ANTARCTICA',
    name_origin: 'Antarctica',
    flag_path: 'AQ.png',
    tel_code: '+6721',
  },
  남수단: {
    code_2: 'SS',
    code_3: 'SSD',
    name: '남수단',
    name_en: 'REPUBLIC OF SOUTH SUDAN',
    name_origin: 'South Sudan',
    flag_path: 'SS.png',
    tel_code: '+211',
  },
  '남아프리카 공화국': {
    code_2: 'ZA',
    code_3: 'ZAF',
    name: '남아프리카 공화국',
    name_en: 'SOUTH AFRICA',
    name_origin: 'South Africa',
    flag_path: 'ZA.png',
    tel_code: '+27',
  },
  네덜란드: {
    code_2: 'NL',
    code_3: 'NLD',
    name: '네덜란드',
    name_en: 'NETHERLANDS',
    name_origin: 'Nederland',
    flag_path: 'NL.png',
    tel_code: '+31',
  },
  '네덜란드령 안틸레스': {
    code_2: 'AN',
    code_3: 'ANT',
    name: '네덜란드령 안틸레스',
    name_en: 'NETHERLANDS ANTILLES',
    name_origin: 'Netherlands Antilles',
    flag_path: 'AN.png',
    tel_code: '+599',
  },
  네팔: {
    code_2: 'NP',
    code_3: 'NPL',
    name: '네팔',
    name_en: 'NEPAL',
    name_origin: 'नेपाल',
    flag_path: 'NP.png',
    tel_code: '+977',
  },
  노르웨이: {
    code_2: 'NO',
    code_3: 'NOR',
    name: '노르웨이',
    name_en: 'NORWAY',
    name_origin: 'Norge',
    flag_path: 'NO.png',
    tel_code: '+47',
  },
  '노퍽 섬': {
    code_2: 'NF',
    code_3: 'NFK',
    name: '노퍽 섬',
    name_en: 'NORFOLK ISLAND',
    name_origin: 'Norfolk Island',
    flag_path: 'NF.png',
    tel_code: '+6723',
  },
  누벨칼레도니: {
    code_2: 'NC',
    code_3: 'NCL',
    name: '누벨칼레도니',
    name_en: 'NEW CALEDONIA',
    name_origin: 'New Caledonia',
    flag_path: 'NC.png',
    tel_code: '+687',
  },
  뉴질랜드: {
    code_2: 'NZ',
    code_3: 'NZL',
    name: '뉴질랜드',
    name_en: 'NEW ZEALAND',
    name_origin: 'New Zealand',
    flag_path: 'NZ.png',
    tel_code: '+64',
  },
  니우에: {
    code_2: 'NU',
    code_3: 'NIU',
    name: '니우에',
    name_en: 'NIUE',
    name_origin: 'Niue',
    flag_path: 'NU.png',
    tel_code: '+683',
  },
  니제르: {
    code_2: 'NE',
    code_3: 'NER',
    name: '니제르',
    name_en: 'NIGER',
    name_origin: 'Niger',
    flag_path: 'NE.png',
    tel_code: '+227',
  },
  니카라과: {
    code_2: 'NI',
    code_3: 'NIC',
    name: '니카라과',
    name_en: 'NICARAGUA',
    name_origin: 'Nicaragua',
    flag_path: 'NI.png',
    tel_code: '+505',
  },
  한국: {
    code_2: 'KR',
    code_3: 'KOR',
    name: '대한민국',
    name_en: 'KOREA, REPUBLIC OF',
    name_origin: '한국',
    flag_path: 'KR.png',
    tel_code: '+82',
  },
  대한민국: {
    code_2: 'KR',
    code_3: 'KOR',
    name: '대한민국',
    name_en: 'KOREA, REPUBLIC OF',
    name_origin: '한국',
    flag_path: 'KR.png',
    tel_code: '+82',
  },
  덴마크: {
    code_2: 'DK',
    code_3: 'DNK',
    name: '덴마크',
    name_en: 'DENMARK',
    name_origin: 'Danmark',
    flag_path: 'DK.png',
    tel_code: '+45',
  },
  '도미니카 공화국': {
    code_2: 'DO',
    code_3: 'DOM',
    name: '도미니카 공화국',
    name_en: 'DOMINICAN REPUBLIC',
    name_origin: 'Dominican Republic',
    flag_path: 'DO.png',
    tel_code: '+1809',
  },
  '도미니카 연방': {
    code_2: 'DM',
    code_3: 'DMA',
    name: '도미니카 연방',
    name_en: 'DOMINICA',
    name_origin: 'Dominica',
    flag_path: 'DM.png',
    tel_code: '+1767',
  },
  독일: {
    code_2: 'DE',
    code_3: 'DEU',
    name: '독일',
    name_en: 'GERMANY',
    name_origin: 'Deutschland',
    flag_path: 'DE.png',
    tel_code: '+49',
  },
  동티모르: {
    code_2: 'TL',
    code_3: 'TLS',
    name: '동티모르',
    name_en: 'EAST TIMOR',
    name_origin: 'Timor-Leste',
    flag_path: 'TL.png',
    tel_code: '+670',
  },
  라오스: {
    code_2: 'LA',
    code_3: 'LAO',
    name: '라오스',
    name_en: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    name_origin: 'ນລາວ',
    flag_path: 'LA.png',
    tel_code: '+856',
  },
  라이베리아: {
    code_2: 'LR',
    code_3: 'LBR',
    name: '라이베리아',
    name_en: 'LIBERIA',
    name_origin: 'Liberia',
    flag_path: 'LR.png',
    tel_code: '+231',
  },
  라트비아: {
    code_2: 'LV',
    code_3: 'LVA',
    name: '라트비아',
    name_en: 'LATVIA',
    name_origin: 'Latvija',
    flag_path: 'LV.png',
    tel_code: '+371',
  },
  러시아: {
    code_2: 'RU',
    code_3: 'RUS',
    name: '러시아',
    name_en: 'RUSSIAN FEDERATION',
    name_origin: 'Россия',
    flag_path: 'RU.png',
    tel_code: '+7',
  },
  레바논: {
    code_2: 'LB',
    code_3: 'LBN',
    name: '레바논',
    name_en: 'LEBANON',
    name_origin: 'لبنان',
    flag_path: 'LB.png',
    tel_code: '+961',
  },
  레소토: {
    code_2: 'LS',
    code_3: 'LSO',
    name: '레소토',
    name_en: 'LESOTHO',
    name_origin: 'Lesotho',
    flag_path: 'LS.png',
    tel_code: '+266',
  },
  레위니옹: {
    code_2: 'RE',
    code_3: 'REU',
    name: '레위니옹',
    name_en: 'REUNION',
    name_origin: 'Reunion',
    flag_path: 'RE.png',
    tel_code: '+262',
  },
  루마니아: {
    code_2: 'RO',
    code_3: 'ROU',
    name: '루마니아',
    name_en: 'ROMANIA',
    name_origin: 'România',
    flag_path: 'RO.png',
    tel_code: '+40',
  },
  룩셈부르크: {
    code_2: 'LU',
    code_3: 'LUX',
    name: '룩셈부르크',
    name_en: 'LUXEMBOURG',
    name_origin: 'Lëtzebuerg',
    flag_path: 'LU.png',
    tel_code: '+352',
  },
  르완다: {
    code_2: 'RW',
    code_3: 'RWA',
    name: '르완다',
    name_en: 'RWANDA',
    name_origin: 'Rwanda',
    flag_path: 'RW.png',
    tel_code: '+250',
  },
  리비아: {
    code_2: 'LY',
    code_3: 'LBY',
    name: '리비아',
    name_en: 'LIBYAN ARAB JAMAHIRIYA',
    name_origin: 'ليبيا',
    flag_path: 'LY.png',
    tel_code: '+218',
  },
  리투아니아: {
    code_2: 'LT',
    code_3: 'LTU',
    name: '리투아니아',
    name_en: 'LITHUANIA',
    name_origin: 'Lietuva',
    flag_path: 'LT.png',
    tel_code: '+370',
  },
  리히텐슈타인: {
    code_2: 'LI',
    code_3: 'LIE',
    name: '리히텐슈타인',
    name_en: 'LIECHTENSTEIN',
    name_origin: 'Liechtenstein',
    flag_path: 'LI.png',
    tel_code: '+423',
  },
  마다가스카르: {
    code_2: 'MG',
    code_3: 'MDG',
    name: '마다가스카르',
    name_en: 'MADAGASCAR',
    name_origin: 'Madagasikara',
    flag_path: 'MG.png',
    tel_code: '+261',
  },
  마르티니크: {
    code_2: 'MQ',
    code_3: 'MTQ',
    name: '마르티니크',
    name_en: 'MARTINIQUE',
    name_origin: 'Martinique',
    flag_path: 'MQ.png',
    tel_code: '+596',
  },
  '마셜 제도': {
    code_2: 'MH',
    code_3: 'MHL',
    name: '마셜 제도',
    name_en: 'MARSHALL ISLANDS',
    name_origin: 'Marshall Islands',
    flag_path: 'MH.png',
    tel_code: '+692',
  },
  마요트: {
    code_2: 'YT',
    code_3: 'MYT',
    name: '마요트',
    name_en: 'MAYOTTE',
    name_origin: 'Mayotte',
    flag_path: 'YT.png',
    tel_code: '+269',
  },
  마카오: {
    code_2: 'MO',
    code_3: 'MAC',
    name: '마카오',
    name_en: 'MACAU',
    name_origin: 'Macao',
    flag_path: 'MO.png',
    tel_code: '+853',
  },
  '마케도니아 공화국': {
    code_2: 'MK',
    code_3: 'MKD',
    name: '마케도니아 공화국',
    name_en: 'REPUBLIC OF MACEDONIA',
    name_origin: 'Македонија',
    flag_path: 'MK.png',
    tel_code: '+389',
  },
  말라위: {
    code_2: 'MW',
    code_3: 'MWI',
    name: '말라위',
    name_en: 'MALAWI',
    name_origin: 'Malawi',
    flag_path: 'MW.png',
    tel_code: '+265',
  },
  말레이시아: {
    code_2: 'MY',
    code_3: 'MYS',
    name: '말레이시아',
    name_en: 'MALAYSIA',
    name_origin: 'Malaysia',
    flag_path: 'MY.png',
    tel_code: '+60',
  },
  말리: {
    code_2: 'ML',
    code_3: 'MLI',
    name: '말리',
    name_en: 'MALI',
    name_origin: 'Mali',
    flag_path: 'ML.png',
    tel_code: '+223',
  },
  '맨 섬': {
    code_2: 'IM',
    code_3: 'IMN',
    name: '맨 섬',
    name_en: 'ISLE OF MAN',
    name_origin: 'Isle of Man',
    flag_path: 'IM.png',
    tel_code: '+441624',
  },
  멕시코: {
    code_2: 'MX',
    code_3: 'MEX',
    name: '멕시코',
    name_en: 'MEXICO',
    name_origin: 'México',
    flag_path: 'MX.png',
    tel_code: '+52',
  },
  모나코: {
    code_2: 'MC',
    code_3: 'MCO',
    name: '모나코',
    name_en: 'MONACO',
    name_origin: 'Monaco',
    flag_path: 'MC.png',
    tel_code: '+377',
  },
  모로코: {
    code_2: 'MA',
    code_3: 'MAR',
    name: '모로코',
    name_en: 'MOROCCO',
    name_origin: 'المغرب',
    flag_path: 'MA.png',
    tel_code: '+212',
  },
  모리셔스: {
    code_2: 'MU',
    code_3: 'MUS',
    name: '모리셔스',
    name_en: 'MAURITIUS',
    name_origin: 'Mauritius',
    flag_path: 'MU.png',
    tel_code: '+230',
  },
  모리타니: {
    code_2: 'MR',
    code_3: 'MRT',
    name: '모리타니',
    name_en: 'MAURITANIA',
    name_origin: 'موريتانيا',
    flag_path: 'MR.png',
    tel_code: '+222',
  },
  모잠비크: {
    code_2: 'MZ',
    code_3: 'MOZ',
    name: '모잠비크',
    name_en: 'MOZAMBIQUE',
    name_origin: 'Moçambique',
    flag_path: 'MZ.png',
    tel_code: '+258',
  },
  몬테네그로: {
    code_2: 'ME',
    code_3: 'MNE',
    name: '몬테네그로',
    name_en: 'MONTENEGRO',
    name_origin: 'Црна Гора',
    flag_path: 'ME.png',
    tel_code: '+382',
  },
  몬트세랫: {
    code_2: 'MS',
    code_3: 'MSR',
    name: '몬트세랫',
    name_en: 'MONTSERRAT',
    name_origin: 'Montserrat',
    flag_path: 'MS.png',
    tel_code: '+1664',
  },
  몰도바: {
    code_2: 'MD',
    code_3: 'MDA',
    name: '몰도바',
    name_en: 'MOLDOVA, REPUBLIC OF',
    name_origin: 'Moldova',
    flag_path: 'MD.png',
    tel_code: '+373',
  },
  몰디브: {
    code_2: 'MV',
    code_3: 'MDV',
    name: '몰디브',
    name_en: 'MALDIVES',
    name_origin: 'ގުޖޭއްރާ ޔާއްރިހޫމްޖ',
    flag_path: 'MV.png',
    tel_code: '+960',
  },
  몰타: {
    code_2: 'MT',
    code_3: 'MLT',
    name: '몰타',
    name_en: 'MALTA',
    name_origin: 'Malta',
    flag_path: 'MT.png',
    tel_code: '+356',
  },
  몽골: {
    code_2: 'MN',
    code_3: 'MNG',
    name: '몽골',
    name_en: 'MONGOLIA',
    name_origin: 'Монгол Улс',
    flag_path: 'MN.png',
    tel_code: '+976',
  },
  미국: {
    code_2: 'US',
    code_3: 'USA',
    name: '미국',
    name_en: 'UNITED STATES',
    name_origin: 'United States',
    flag_path: 'US.png',
    tel_code: '+1',
  },
  '미국령 군소 제도': {
    code_2: 'UM',
    code_3: 'UMI',
    name: '미국령 군소 제도',
    name_en: 'UNITED STATES MINOR OUTLYING ISLANDS',
    name_origin: 'United States minor outlying islands',
    flag_path: 'UM.png',
    tel_code: '+0',
  },
  '미국령 버진아일랜드': {
    code_2: 'VI',
    code_3: 'VIR',
    name: '미국령 버진아일랜드',
    name_en: 'VIRGIN ISLANDS, U.S.',
    name_origin: 'Virgin Islands, U.S.',
    flag_path: 'VI.png',
    tel_code: '+1340',
  },
  미얀마: {
    code_2: 'MM',
    code_3: 'MMR',
    name: '미얀마',
    name_en: 'MYANMAR',
    name_origin: 'Myanmar(Burma)',
    flag_path: 'MM.png',
    tel_code: '+95',
  },
  '미크로네시아 연방': {
    code_2: 'FM',
    code_3: 'FSM',
    name: '미크로네시아 연방',
    name_en: 'MICRONESIA',
    name_origin: 'Micronesia',
    flag_path: 'FM.png',
    tel_code: '+691',
  },
  바누아투: {
    code_2: 'VU',
    code_3: 'VUT',
    name: '바누아투',
    name_en: 'VANUATU',
    name_origin: 'Vanuatu',
    flag_path: 'VU.png',
    tel_code: '+678',
  },
  바레인: {
    code_2: 'BH',
    code_3: 'BHR',
    name: '바레인',
    name_en: 'BAHRAIN',
    name_origin: 'البحرين',
    flag_path: 'BH.png',
    tel_code: '+973',
  },
  바베이도스: {
    code_2: 'BB',
    code_3: 'BRB',
    name: '바베이도스',
    name_en: 'BARBADOS',
    name_origin: 'Barbados',
    flag_path: 'BB.png',
    tel_code: '+1246',
  },
  '바티칸 시국': {
    code_2: 'VA',
    code_3: 'VAT',
    name: '바티칸 시국',
    name_en: 'VATICAN CITY STATE',
    name_origin: 'Città del Vaticano',
    flag_path: 'VA.png',
    tel_code: '+379',
  },
  바하마: {
    code_2: 'BS',
    code_3: 'BHS',
    name: '바하마',
    name_en: 'BAHAMAS',
    name_origin: 'Bahamas',
    flag_path: 'BS.png',
    tel_code: '+1242',
  },
  방글라데시: {
    code_2: 'BD',
    code_3: 'BGD',
    name: '방글라데시',
    name_en: 'BANGLADESH',
    name_origin: 'বাংলাদেশ',
    flag_path: 'BD.png',
    tel_code: '+880',
  },
  버뮤다: {
    code_2: 'BM',
    code_3: 'BMU',
    name: '버뮤다',
    name_en: 'BERMUDA',
    name_origin: 'Bermuda',
    flag_path: 'BM.png',
    tel_code: '+1441',
  },
  베냉: {
    code_2: 'BJ',
    code_3: 'BEN',
    name: '베냉',
    name_en: 'BENIN',
    name_origin: 'Bénin',
    flag_path: 'BJ.png',
    tel_code: '+229',
  },
  베네수엘라: {
    code_2: 'VE',
    code_3: 'VEN',
    name: '베네수엘라',
    name_en: 'VENEZUELA',
    name_origin: 'Venezuela',
    flag_path: 'VE.png',
    tel_code: '+58',
  },
  베트남: {
    code_2: 'VN',
    code_3: 'VNM',
    name: '베트남',
    name_en: 'VIET NAM',
    name_origin: 'Việt Nam',
    flag_path: 'VN.png',
    tel_code: '+84',
  },
  벨기에: {
    code_2: 'BE',
    code_3: 'BEL',
    name: '벨기에',
    name_en: 'BELGIUM',
    name_origin: 'België',
    flag_path: 'BE.png',
    tel_code: '+32',
  },
  벨라루스: {
    code_2: 'BY',
    code_3: 'BLR',
    name: '벨라루스',
    name_en: 'BELARUS',
    name_origin: 'Белару́сь',
    flag_path: 'BY.png',
    tel_code: '+375',
  },
  벨리즈: {
    code_2: 'BZ',
    code_3: 'BLZ',
    name: '벨리즈',
    name_en: 'BELIZE',
    name_origin: 'Belize',
    flag_path: 'BZ.png',
    tel_code: '+501',
  },
  '보스니아 헤르체고비나': {
    code_2: 'BA',
    code_3: 'BIH',
    name: '보스니아 헤르체고비나',
    name_en: 'BOSNIA HERCEGOVINA',
    name_origin: 'Bosna i Hercegovina',
    flag_path: 'BA.png',
    tel_code: '+387',
  },
  보츠와나: {
    code_2: 'BW',
    code_3: 'BWA',
    name: '보츠와나',
    name_en: 'BOTSWANA',
    name_origin: 'Botswana',
    flag_path: 'BW.png',
    tel_code: '+267',
  },
  볼리비아: {
    code_2: 'BO',
    code_3: 'BOL',
    name: '볼리비아',
    name_en: 'BOLIVIA',
    name_origin: 'Bolivia',
    flag_path: 'BO.png',
    tel_code: '+591',
  },
  부룬디: {
    code_2: 'BI',
    code_3: 'BDI',
    name: '부룬디',
    name_en: 'BURUNDI',
    name_origin: 'Uburundi',
    flag_path: 'BI.png',
    tel_code: '+257',
  },
  부르키나파소: {
    code_2: 'BF',
    code_3: 'BFA',
    name: '부르키나파소',
    name_en: 'BURKINA FASO',
    name_origin: 'Burkina Faso',
    flag_path: 'BF.png',
    tel_code: '+226',
  },
  '부베 섬': {
    code_2: 'BV',
    code_3: 'BVT',
    name: '부베 섬',
    name_en: 'BOUVET ISLAND',
    name_origin: 'Bouvet Island',
    flag_path: 'BV.png',
    tel_code: '+47',
  },
  부탄: {
    code_2: 'BT',
    code_3: 'BTN',
    name: '부탄',
    name_en: 'BHUTAN',
    name_origin: 'འབྲུག་ཡུལ',
    flag_path: 'BT.png',
    tel_code: '+975',
  },
  '북마리아나 제도': {
    code_2: 'MP',
    code_3: 'MNP',
    name: '북마리아나 제도',
    name_en: 'NORTHERN MARIANA ISLANDS',
    name_origin: 'Northern Mariana Islands',
    flag_path: 'MP.png',
    tel_code: '+1670',
  },
  불가리아: {
    code_2: 'BG',
    code_3: 'BGR',
    name: '불가리아',
    name_en: 'BULGARIA',
    name_origin: 'България',
    flag_path: 'BG.png',
    tel_code: '+359',
  },
  브라질: {
    code_2: 'BR',
    code_3: 'BRA',
    name: '브라질',
    name_en: 'BRAZIL',
    name_origin: 'Brasil',
    flag_path: 'BR.png',
    tel_code: '+55',
  },
  브루나이: {
    code_2: 'BN',
    code_3: 'BRN',
    name: '브루나이',
    name_en: 'BRUNEI DARUSSALAM',
    name_origin: 'Brunei Darussalam',
    flag_path: 'BN.png',
    tel_code: '+673',
  },
  사모아: {
    code_2: 'WS',
    code_3: 'WSM',
    name: '사모아',
    name_en: 'SAMOA',
    name_origin: 'Samoa',
    flag_path: 'WS.png',
    tel_code: '+685',
  },
  사우디아라비아: {
    code_2: 'SA',
    code_3: 'SAU',
    name: '사우디아라비아',
    name_en: 'SAUDI ARABIA',
    name_origin: 'المملكة العربية السعودية',
    flag_path: 'SA.png',
    tel_code: '+966',
  },
  '사우스조지아 사우스샌드위치 제도': {
    code_2: 'GS',
    code_3: 'SGS',
    name: '사우스조지아 사우스샌드위치 제도',
    name_en: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    name_origin: 'South Georgia and the South Sandwich Islands',
    flag_path: 'GS.png',
    tel_code: '+44',
  },
  산마리노: {
    code_2: 'SM',
    code_3: 'SMR',
    name: '산마리노',
    name_en: 'SAN MARINO',
    name_origin: 'San Marino',
    flag_path: 'SM.png',
    tel_code: '+378',
  },
  '상투메 프린시페': {
    code_2: 'ST',
    code_3: 'STP',
    name: '상투메 프린시페',
    name_en: 'SAO TOME AND PRINCIPE',
    name_origin: 'São Tomé and Príncipe',
    flag_path: 'ST.png',
    tel_code: '+239',
  },
  '생피에르 미클롱': {
    code_2: 'PM',
    code_3: 'SPM',
    name: '생피에르 미클롱',
    name_en: 'ST. PIERRE AND MIQUELON',
    name_origin: 'Saint Pierre and Miquelon',
    flag_path: 'PM.png',
    tel_code: '+508',
  },
  서사하라: {
    code_2: 'EH',
    code_3: 'ESH',
    name: '서사하라',
    name_en: 'WESTERN SAHARA',
    name_origin: 'الصحراء الغربية',
    flag_path: 'EH.png',
    tel_code: '+212',
  },
  세네갈: {
    code_2: 'SN',
    code_3: 'SEN',
    name: '세네갈',
    name_en: 'SENEGAL',
    name_origin: 'Sénégal',
    flag_path: 'SN.png',
    tel_code: '+221',
  },
  세르비아: {
    code_2: 'RS',
    code_3: 'SRB',
    name: '세르비아',
    name_en: 'SERBIA',
    name_origin: 'Србија',
    flag_path: 'RS.png',
    tel_code: '+381',
  },
  세이셸: {
    code_2: 'SC',
    code_3: 'SYC',
    name: '세이셸',
    name_en: 'SEYCHELLES',
    name_origin: 'Seychelles',
    flag_path: 'SC.png',
    tel_code: '+248',
  },
  세인트루시아: {
    code_2: 'LC',
    code_3: 'LCA',
    name: '세인트루시아',
    name_en: 'SAINT LUCIA',
    name_origin: 'Saint Lucia',
    flag_path: 'LC.png',
    tel_code: '+1758',
  },
  '세인트빈센트 그레나딘': {
    code_2: 'VC',
    code_3: 'VCT',
    name: '세인트빈센트 그레나딘',
    name_en: 'SAINT VINCENT AND THE GRENADINES',
    name_origin: 'Saint Vincent and the Grenadines',
    flag_path: 'VC.png',
    tel_code: '+1784',
  },
  '세인트키츠 네비스': {
    code_2: 'KN',
    code_3: 'KNA',
    name: '세인트키츠 네비스',
    name_en: 'SAINT KITTS AND NEVIS',
    name_origin: 'Saint Kitts and Nevis',
    flag_path: 'KN.png',
    tel_code: '+1869',
  },
  세인트헬레나: {
    code_2: 'SH',
    code_3: 'SHN',
    name: '세인트헬레나',
    name_en: 'ST. HELENA',
    name_origin: 'Saint Helena',
    flag_path: 'SH.png',
    tel_code: '+290',
  },
  소말리아: {
    code_2: 'SO',
    code_3: 'SOM',
    name: '소말리아',
    name_en: 'SOMALIA',
    name_origin: 'Soomaaliya',
    flag_path: 'SO.png',
    tel_code: '+252',
  },
  '솔로몬 제도': {
    code_2: 'SB',
    code_3: 'SLB',
    name: '솔로몬 제도',
    name_en: 'SOLOMON ISLANDS',
    name_origin: 'Solomon Islands',
    flag_path: 'SB.png',
    tel_code: '+677',
  },
  수단: {
    code_2: 'SD',
    code_3: 'SDN',
    name: '수단',
    name_en: 'SUDAN',
    name_origin: 'السودان',
    flag_path: 'SD.png',
    tel_code: '+249',
  },
  수리남: {
    code_2: 'SR',
    code_3: 'SUR',
    name: '수리남',
    name_en: 'SURINAME',
    name_origin: 'Suriname',
    flag_path: 'SR.png',
    tel_code: '+597',
  },
  스리랑카: {
    code_2: 'LK',
    code_3: 'LKA',
    name: '스리랑카',
    name_en: 'SRI LANKA',
    name_origin: 'Sri Lanka',
    flag_path: 'LK.png',
    tel_code: '+94',
  },
  '스발바르 얀마옌': {
    code_2: 'SJ',
    code_3: 'SJM',
    name: '스발바르 얀마옌',
    name_en: 'SVALBARD AND JAN MAYEN ISLANDS',
    name_origin: 'Svalbard and Jan Mayen',
    flag_path: 'SJ.png',
    tel_code: '+47',
  },
  스와질란드: {
    code_2: 'SZ',
    code_3: 'SWZ',
    name: '스와질란드',
    name_en: 'SWAZILAND',
    name_origin: 'Swaziland',
    flag_path: 'SZ.png',
    tel_code: '+268',
  },
  스웨덴: {
    code_2: 'SE',
    code_3: 'SWE',
    name: '스웨덴',
    name_en: 'SWEDEN',
    name_origin: 'Sverige',
    flag_path: 'SE.png',
    tel_code: '+46',
  },
  스위스: {
    code_2: 'CH',
    code_3: 'CHE',
    name: '스위스',
    name_en: 'SWITZERLAND',
    name_origin: 'Schweiz',
    flag_path: 'CH.png',
    tel_code: '+41',
  },
  스페인: {
    code_2: 'ES',
    code_3: 'ESP',
    name: '스페인',
    name_en: 'SPAIN',
    name_origin: 'España',
    flag_path: 'ES.png',
    tel_code: '+34',
  },
  슬로바키아: {
    code_2: 'SK',
    code_3: 'SVK',
    name: '슬로바키아',
    name_en: 'SLOVAKIA',
    name_origin: 'Slovensko',
    flag_path: 'SK.png',
    tel_code: '+421',
  },
  슬로베니아: {
    code_2: 'SI',
    code_3: 'SVN',
    name: '슬로베니아',
    name_en: 'SLOVENIA',
    name_origin: 'Slovenija',
    flag_path: 'SI.png',
    tel_code: '+386',
  },
  시리아: {
    code_2: 'SY',
    code_3: 'SYR',
    name: '시리아',
    name_en: 'SYRIAN ARAB REPUBLIC',
    name_origin: 'سوريا',
    flag_path: 'SY.png',
    tel_code: '+963',
  },
  시에라리온: {
    code_2: 'SL',
    code_3: 'SLE',
    name: '시에라리온',
    name_en: 'SIERRA LEONE',
    name_origin: 'Sierra Leone',
    flag_path: 'SL.png',
    tel_code: '+232',
  },
  신트마르턴: {
    code_2: 'SX',
    code_3: 'SXM',
    name: '신트마르턴',
    name_en: 'Sint Maarten',
    name_origin: 'Eilandgebied Sint Maarten',
    flag_path: 'SX.png',
    tel_code: '+1721',
  },
  싱가포르: {
    code_2: 'SG',
    code_3: 'SGP',
    name: '싱가포르',
    name_en: 'SINGAPORE',
    name_origin: 'Singapura',
    flag_path: 'SG.png',
    tel_code: '+65',
  },
  아랍에미리트: {
    code_2: 'AE',
    code_3: 'ARE',
    name: '아랍에미리트',
    name_en: 'UNITED ARAB EMIRATES',
    name_origin: 'الإمارات العربيّة المتّحدة',
    flag_path: 'AE.png',
    tel_code: '+971',
  },
  아루바: {
    code_2: 'AW',
    code_3: 'ABW',
    name: '아루바',
    name_en: 'ARUBA',
    name_origin: 'Aruba',
    flag_path: 'AW.png',
    tel_code: '+297',
  },
  아르메니아: {
    code_2: 'AM',
    code_3: 'ARM',
    name: '아르메니아',
    name_en: 'ARMENIA',
    name_origin: 'Հայաստան',
    flag_path: 'AM.png',
    tel_code: '+374',
  },
  아르헨티나: {
    code_2: 'AR',
    code_3: 'ARG',
    name: '아르헨티나',
    name_en: 'ARGENTINA',
    name_origin: 'Argentina',
    flag_path: 'AR.png',
    tel_code: '+54',
  },
  아메리칸사모아: {
    code_2: 'AS',
    code_3: 'ASM',
    name: '아메리칸사모아',
    name_en: 'AMERICAN SAMOA',
    name_origin: 'American Samoa',
    flag_path: 'AS.png',
    tel_code: '+1684',
  },
  아이슬란드: {
    code_2: 'IS',
    code_3: 'ISL',
    name: '아이슬란드',
    name_en: 'ICELAND',
    name_origin: 'Ísland',
    flag_path: 'IS.png',
    tel_code: '+354',
  },
  아이티: {
    code_2: 'HT',
    code_3: 'HTI',
    name: '아이티',
    name_en: 'HAITI',
    name_origin: 'Haïti',
    flag_path: 'HT.png',
    tel_code: '+509',
  },
  아일랜드: {
    code_2: 'IE',
    code_3: 'IRL',
    name: '아일랜드',
    name_en: 'IRELAND',
    name_origin: 'Ireland',
    flag_path: 'IE.png',
    tel_code: '+353',
  },
  아제르바이잔: {
    code_2: 'AZ',
    code_3: 'AZE',
    name: '아제르바이잔',
    name_en: 'AZERBAIJAN',
    name_origin: 'Azərbaycan',
    flag_path: 'AZ.png',
    tel_code: '+994',
  },
  아프가니스탄: {
    code_2: 'AF',
    code_3: 'AFG',
    name: '아프가니스탄',
    name_en: 'AFGHANISTAN',
    name_origin: 'افغانستان',
    flag_path: 'AF.png',
    tel_code: '+93',
  },
  안도라: {
    code_2: 'AD',
    code_3: 'AND',
    name: '안도라',
    name_en: 'ANDORRA',
    name_origin: 'Andorra',
    flag_path: 'AD.png',
    tel_code: '+376',
  },
  알바니아: {
    code_2: 'AL',
    code_3: 'ALB',
    name: '알바니아',
    name_en: 'ALBANIA',
    name_origin: 'Shqipëria',
    flag_path: 'AL.png',
    tel_code: '+355',
  },
  알제리: {
    code_2: 'DZ',
    code_3: 'DZA',
    name: '알제리',
    name_en: 'ALGERIA',
    name_origin: 'الجزائر',
    flag_path: 'DZ.png',
    tel_code: '+213',
  },
  앙골라: {
    code_2: 'AO',
    code_3: 'AGO',
    name: '앙골라',
    name_en: 'ANGOLA',
    name_origin: 'Angola',
    flag_path: 'AO.png',
    tel_code: '+244',
  },
  '앤티가 바부다': {
    code_2: 'AG',
    code_3: 'ATG',
    name: '앤티가 바부다',
    name_en: 'ANTIGUA AND BARBUDA',
    name_origin: 'Antigua and Barbuda',
    flag_path: 'AG.png',
    tel_code: '+1268',
  },
  앵귈라: {
    code_2: 'AI',
    code_3: 'AIA',
    name: '앵귈라',
    name_en: 'ANGUILLA',
    name_origin: 'Anguilla',
    flag_path: 'AI.png',
    tel_code: '+1264',
  },
  에리트레아: {
    code_2: 'ER',
    code_3: 'ERI',
    name: '에리트레아',
    name_en: 'ERITREA',
    name_origin: 'Ertra',
    flag_path: 'ER.png',
    tel_code: '+291',
  },
  에스토니아: {
    code_2: 'EE',
    code_3: 'EST',
    name: '에스토니아',
    name_en: 'ESTONIA',
    name_origin: 'Eesti',
    flag_path: 'EE.png',
    tel_code: '+372',
  },
  에콰도르: {
    code_2: 'EC',
    code_3: 'ECU',
    name: '에콰도르',
    name_en: 'ECUADOR',
    name_origin: 'Ecuador',
    flag_path: 'EC.png',
    tel_code: '+593',
  },
  에티오피아: {
    code_2: 'ET',
    code_3: 'ETH',
    name: '에티오피아',
    name_en: 'ETHIOPIA',
    name_origin: "Ityop'iya",
    flag_path: 'ET.png',
    tel_code: '+251',
  },
  엘살바도르: {
    code_2: 'SV',
    code_3: 'SLV',
    name: '엘살바도르',
    name_en: 'EL SALVADOR',
    name_origin: 'El Salvador',
    flag_path: 'SV.png',
    tel_code: '+503',
  },
  영국: {
    code_2: 'GB',
    code_3: 'GBR',
    name: '영국',
    name_en: 'UNITED KINGDOM',
    name_origin: 'United Kingdom',
    flag_path: 'GB.png',
    tel_code: '+44',
  },
  '영국령 버진아일랜드': {
    code_2: 'VG',
    code_3: 'VGB',
    name: '영국령 버진아일랜드',
    name_en: 'VIRGIN ISLANDS, BRITISH',
    name_origin: 'Virgin Islands, British',
    flag_path: 'VG.png',
    tel_code: '+1284',
  },
  '영국령 인도양 지역': {
    code_2: 'IO',
    code_3: 'IOT',
    name: '영국령 인도양 지역',
    name_en: 'BRITISH INDIAN OCEAN TERRITORY',
    name_origin: 'British Indian Ocean Territory',
    flag_path: 'IO.png',
    tel_code: '+246',
  },
  예멘: {
    code_2: 'YE',
    code_3: 'YEM',
    name: '예멘',
    name_en: 'YEMEN, REPUBLIC OF',
    name_origin: 'اليمن',
    flag_path: 'YE.png',
    tel_code: '+967',
  },
  오만: {
    code_2: 'OM',
    code_3: 'OMN',
    name: '오만',
    name_en: 'OMAN',
    name_origin: 'عمان',
    flag_path: 'OM.png',
    tel_code: '+968',
  },
  오스트레일리아: {
    code_2: 'AU',
    code_3: 'AUS',
    name: '오스트레일리아',
    name_en: 'AUSTRALIA',
    name_origin: 'Australia',
    flag_path: 'AU.png',
    tel_code: '+61',
  },
  오스트리아: {
    code_2: 'AT',
    code_3: 'AUT',
    name: '오스트리아',
    name_en: 'AUSTRIA',
    name_origin: 'Österreich',
    flag_path: 'AT.png',
    tel_code: '+43',
  },
  온두라스: {
    code_2: 'HN',
    code_3: 'HND',
    name: '온두라스',
    name_en: 'HONDURAS',
    name_origin: 'Honduras',
    flag_path: 'HN.png',
    tel_code: '+504',
  },
  '올란드 제도': {
    code_2: 'AX',
    code_3: 'ALA',
    name: '올란드 제도',
    name_en: 'ALAND ISLANDS',
    name_origin: 'Aland Islands',
    flag_path: 'AX.png',
    tel_code: '+35818',
  },
  '왈리스 퓌튀나': {
    code_2: 'WF',
    code_3: 'WLF',
    name: '왈리스 퓌튀나',
    name_en: 'WALLIS AND FUTUNA ISLANDS',
    name_origin: 'Wallis and Futuna',
    flag_path: 'WF.png',
    tel_code: '+681',
  },
  요르단: {
    code_2: 'JO',
    code_3: 'JOR',
    name: '요르단',
    name_en: 'JORDAN',
    name_origin: 'الاردن',
    flag_path: 'JO.png',
    tel_code: '+962',
  },
  우간다: {
    code_2: 'UG',
    code_3: 'UGA',
    name: '우간다',
    name_en: 'UGANDA',
    name_origin: 'Uganda',
    flag_path: 'UG.png',
    tel_code: '+256',
  },
  우루과이: {
    code_2: 'UY',
    code_3: 'URY',
    name: '우루과이',
    name_en: 'URUGUAY',
    name_origin: 'Uruguay',
    flag_path: 'UY.png',
    tel_code: '+598',
  },
  우즈베키스탄: {
    code_2: 'UZ',
    code_3: 'UZB',
    name: '우즈베키스탄',
    name_en: 'UZBEKISTAN',
    name_origin: "O'zbekiston",
    flag_path: 'UZ.png',
    tel_code: '+998',
  },
  우크라이나: {
    code_2: 'UA',
    code_3: 'UKR',
    name: '우크라이나',
    name_en: 'UKRAINE',
    name_origin: 'Україна',
    flag_path: 'UA.png',
    tel_code: '+380',
  },
  이라크: {
    code_2: 'IQ',
    code_3: 'IRQ',
    name: '이라크',
    name_en: 'IRAQ',
    name_origin: 'العراق',
    flag_path: 'IQ.png',
    tel_code: '+98',
  },
  이란: {
    code_2: 'IR',
    code_3: 'IRN',
    name: '이란',
    name_en: 'IRAN',
    name_origin: 'ایران',
    flag_path: 'IR.png',
    tel_code: '+964',
  },
  이스라엘: {
    code_2: 'IL',
    code_3: 'ISR',
    name: '이스라엘',
    name_en: 'ISRAEL',
    name_origin: 'ישראל',
    flag_path: 'IL.png',
    tel_code: '+972',
  },
  이집트: {
    code_2: 'EG',
    code_3: 'EGY',
    name: '이집트',
    name_en: 'EGYPT',
    name_origin: 'مصر',
    flag_path: 'EG.png',
    tel_code: '+20',
  },
  이탈리아: {
    code_2: 'IT',
    code_3: 'ITA',
    name: '이탈리아',
    name_en: 'ITALY',
    name_origin: 'Italia',
    flag_path: 'IT.png',
    tel_code: '+39',
  },
  인도: {
    code_2: 'IN',
    code_3: 'IND',
    name: '인도',
    name_en: 'INDIA',
    name_origin: 'India',
    flag_path: 'IN.png',
    tel_code: '+91',
  },
  인도네시아: {
    code_2: 'ID',
    code_3: 'IDN',
    name: '인도네시아',
    name_en: 'INDONESIA',
    name_origin: 'Indonesia',
    flag_path: 'ID.png',
    tel_code: '+62',
  },
  일본: {
    code_2: 'JP',
    code_3: 'JPN',
    name: '일본',
    name_en: 'JAPAN',
    name_origin: '日本',
    flag_path: 'JP.png',
    tel_code: '+81',
  },
  자메이카: {
    code_2: 'JM',
    code_3: 'JAM',
    name: '자메이카',
    name_en: 'JAMAICA',
    name_origin: 'Jamaica',
    flag_path: 'JM.png',
    tel_code: '+1876',
  },
  잠비아: {
    code_2: 'ZM',
    code_3: 'ZMB',
    name: '잠비아',
    name_en: 'ZAMBIA',
    name_origin: 'Zambia',
    flag_path: 'ZM.png',
    tel_code: '+260',
  },
  '저지 섬': {
    code_2: 'JE',
    code_3: 'JEY',
    name: '저지 섬',
    name_en: 'JERSEY',
    name_origin: 'Jersey',
    flag_path: 'JE.png',
    tel_code: '+441534',
  },
  '적도 기니': {
    code_2: 'GQ',
    code_3: 'GNQ',
    name: '적도 기니',
    name_en: 'EQUATORIAL GUINEA',
    name_origin: 'Guinea Ecuatorial',
    flag_path: 'GQ.png',
    tel_code: '+240',
  },
  조선민주주의인민공화국: {
    code_2: 'KP',
    code_3: 'PRK',
    name: '조선민주주의인민공화국',
    name_en: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    name_origin: '조선',
    flag_path: 'KP.png',
    tel_code: '+850',
  },
  '중앙아프리카 공화국': {
    code_2: 'CF',
    code_3: 'CAF',
    name: '중앙아프리카 공화국',
    name_en: 'CENTRAL AFRICAN REPUBLIC',
    name_origin: 'République Centrafricaine',
    flag_path: 'CF.png',
    tel_code: '+236',
  },
  대만: {
    code_2: 'TW',
    code_3: 'TWN',
    name: '중화민국',
    name_en: 'TAIWAN, PROVINCE OF CHINA',
    name_origin: '台灣',
    flag_path: 'TW.png',
    tel_code: '+886',
  },
  중국: {
    code_2: 'CN',
    code_3: 'CHN',
    name: '중화인민공화국',
    name_en: 'CHINA',
    name_origin: '中国',
    flag_path: 'CN.png',
    tel_code: '+86',
  },
  지부티: {
    code_2: 'DJ',
    code_3: 'DJI',
    name: '지부티',
    name_en: 'DJIBOUTI',
    name_origin: 'Djibouti',
    flag_path: 'DJ.png',
    tel_code: '+253',
  },
  지브롤터: {
    code_2: 'GI',
    code_3: 'GIB',
    name: '지브롤터',
    name_en: 'GIBRALTAR',
    name_origin: 'Gibraltar',
    flag_path: 'GI.png',
    tel_code: '+350',
  },
  짐바브웨: {
    code_2: 'ZW',
    code_3: 'ZWE',
    name: '짐바브웨',
    name_en: 'ZIMBABWE',
    name_origin: 'Zimbabwe',
    flag_path: 'ZW.png',
    tel_code: '+263',
  },
  차드: {
    code_2: 'TD',
    code_3: 'TCD',
    name: '차드',
    name_en: 'CHAD',
    name_origin: 'Tchad',
    flag_path: 'TD.png',
    tel_code: '+235',
  },
  체코: {
    code_2: 'CZ',
    code_3: 'CZE',
    name: '체코',
    name_en: 'CZECH REPUBLIC',
    name_origin: 'Česko',
    flag_path: 'CZ.png',
    tel_code: '+420',
  },
  칠레: {
    code_2: 'CL',
    code_3: 'CHL',
    name: '칠레',
    name_en: 'CHILE',
    name_origin: 'Chile',
    flag_path: 'CL.png',
    tel_code: '+56',
  },
  카메룬: {
    code_2: 'CM',
    code_3: 'CMR',
    name: '카메룬',
    name_en: 'CAMEROON',
    name_origin: 'Cameroun',
    flag_path: 'CM.png',
    tel_code: '+237',
  },
  카보베르데: {
    code_2: 'CV',
    code_3: 'CPV',
    name: '카보베르데',
    name_en: 'CAPE VERDE',
    name_origin: 'Cabo Verde',
    flag_path: 'CV.png',
    tel_code: '+238',
  },
  카자흐스탄: {
    code_2: 'KZ',
    code_3: 'KAZ',
    name: '카자흐스탄',
    name_en: 'KAZAKHSTAN',
    name_origin: 'Қазақстан',
    flag_path: 'KZ.png',
    tel_code: '+7',
  },
  카타르: {
    code_2: 'QA',
    code_3: 'QAT',
    name: '카타르',
    name_en: 'QATAR',
    name_origin: 'قطر',
    flag_path: 'QA.png',
    tel_code: '+974',
  },
  캄보디아: {
    code_2: 'KH',
    code_3: 'KHM',
    name: '캄보디아',
    name_en: 'CAMBODIA',
    name_origin: 'Kampuchea',
    flag_path: 'KH.png',
    tel_code: '+855',
  },
  캐나다: {
    code_2: 'CA',
    code_3: 'CAN',
    name: '캐나다',
    name_en: 'CANADA',
    name_origin: 'Canada',
    flag_path: 'CA.png',
    tel_code: '+1',
  },
  케냐: {
    code_2: 'KE',
    code_3: 'KEN',
    name: '케냐',
    name_en: 'KENYA',
    name_origin: 'Kenya',
    flag_path: 'KE.png',
    tel_code: '+254',
  },
  '케이맨 제도': {
    code_2: 'KY',
    code_3: 'CYM',
    name: '케이맨 제도',
    name_en: 'CAYMAN ISLANDS',
    name_origin: 'Cayman Islands',
    flag_path: 'KY.png',
    tel_code: '+1345',
  },
  코모로: {
    code_2: 'KM',
    code_3: 'COM',
    name: '코모로',
    name_en: 'COMOROS',
    name_origin: 'Comores',
    flag_path: 'KM.png',
    tel_code: '+269',
  },
  코스타리카: {
    code_2: 'CR',
    code_3: 'CRI',
    name: '코스타리카',
    name_en: 'COSTA RICA',
    name_origin: 'Costa Rica',
    flag_path: 'CR.png',
    tel_code: '+506',
  },
  '코코스 제도': {
    code_2: 'CC',
    code_3: 'CCK',
    name: '코코스 제도',
    name_en: 'COCOS ISLANDS',
    name_origin: 'Cocos Islands',
    flag_path: 'CC.png',
    tel_code: '+6189162',
  },
  코트디부아르: {
    code_2: 'CI',
    code_3: 'CIV',
    name: '코트디부아르',
    name_en: "COTE D'IVOIRE",
    name_origin: "Côte d'Ivoire",
    flag_path: 'CI.png',
    tel_code: '+225',
  },
  콜롬비아: {
    code_2: 'CO',
    code_3: 'COL',
    name: '콜롬비아',
    name_en: 'COLOMBIA',
    name_origin: 'Colombia',
    flag_path: 'CO.png',
    tel_code: '+57',
  },
  '콩고 공화국': {
    code_2: 'CG',
    code_3: 'COG',
    name: '콩고 공화국',
    name_en: 'CONGO',
    name_origin: 'Congo',
    flag_path: 'CG.png',
    tel_code: '+242',
  },
  '콩고 민주 공화국': {
    code_2: 'CD',
    code_3: 'COD',
    name: '콩고 민주 공화국',
    name_en: 'DEMOCRATIC REPUBLIC OF THE CONGO',
    name_origin: 'Congo, Democratic Republic of the',
    flag_path: 'CD.png',
    tel_code: '+243',
  },
  쿠바: {
    code_2: 'CU',
    code_3: 'CUB',
    name: '쿠바',
    name_en: 'CUBA',
    name_origin: 'Cuba',
    flag_path: 'CU.png',
    tel_code: '+53',
  },
  쿠웨이트: {
    code_2: 'KW',
    code_3: 'KWT',
    name: '쿠웨이트',
    name_en: 'KUWAIT',
    name_origin: 'الكويت',
    flag_path: 'KW.png',
    tel_code: '+965',
  },
  '쿡 제도': {
    code_2: 'CK',
    code_3: 'COK',
    name: '쿡 제도',
    name_en: 'COOK ISLANDS',
    name_origin: 'Cook Islands',
    flag_path: 'CK.png',
    tel_code: '+682',
  },
  크로아티아: {
    code_2: 'HR',
    code_3: 'HRV',
    name: '크로아티아',
    name_en: 'CROATIA',
    name_origin: 'Hrvatska',
    flag_path: 'HR.png',
    tel_code: '+385',
  },
  '크리스마스 섬': {
    code_2: 'CX',
    code_3: 'CXR',
    name: '크리스마스 섬',
    name_en: 'CHRISTMAS ISLAND',
    name_origin: 'Christmas Island',
    flag_path: 'CX.png',
    tel_code: '+6189164',
  },
  키르기스스탄: {
    code_2: 'KG',
    code_3: 'KGZ',
    name: '키르기스스탄',
    name_en: 'KYRGYZSTAN',
    name_origin: 'Кыргызстан',
    flag_path: 'KG.png',
    tel_code: '+996',
  },
  키리바시: {
    code_2: 'KI',
    code_3: 'KIR',
    name: '키리바시',
    name_en: 'KIRIBATI',
    name_origin: 'Kiribati',
    flag_path: 'KI.png',
    tel_code: '+686',
  },
  키프로스: {
    code_2: 'CY',
    code_3: 'CYP',
    name: '키프로스',
    name_en: 'CYPRUS',
    name_origin: 'Κυπρος',
    flag_path: 'CY.png',
    tel_code: '+357',
  },
  타이: {
    code_2: 'TH',
    code_3: 'THA',
    name: '타이',
    name_en: 'THAILAND',
    name_origin: 'ราชอาณาจักรไทย',
    flag_path: 'TH.png',
    tel_code: '+66',
  },
  태국: {
    code_2: 'TH',
    code_3: 'THA',
    name: '타이',
    name_en: 'THAILAND',
    name_origin: 'ราชอาณาจักรไทย',
    flag_path: 'TH.png',
    tel_code: '+66',
  },
  타지키스탄: {
    code_2: 'TJ',
    code_3: 'TJK',
    name: '타지키스탄',
    name_en: 'TAJIKISTAN',
    name_origin: 'Тоҷикистон',
    flag_path: 'TJ.png',
    tel_code: '+992',
  },
  탄자니아: {
    code_2: 'TZ',
    code_3: 'TZA',
    name: '탄자니아',
    name_en: 'TANZANIA, UNITED REPUBLIC OF',
    name_origin: 'Tanzania',
    flag_path: 'TZ.png',
    tel_code: '+255',
  },
  '터크스 케이커스 제도': {
    code_2: 'TC',
    code_3: 'TCA',
    name: '터크스 케이커스 제도',
    name_en: 'TURKS AND CAICOS ISLANDS',
    name_origin: 'Turks and Caicos Islands',
    flag_path: 'TC.png',
    tel_code: '+1649',
  },
  터키: {
    code_2: 'TR',
    code_3: 'TUR',
    name: '터키',
    name_en: 'TURKEY',
    name_origin: 'Türkiye',
    flag_path: 'TR.png',
    tel_code: '+90',
  },
  토고: {
    code_2: 'TG',
    code_3: 'TGO',
    name: '토고',
    name_en: 'TOGO',
    name_origin: 'Togo',
    flag_path: 'TG.png',
    tel_code: '+228',
  },
  토켈라우: {
    code_2: 'TK',
    code_3: 'TKL',
    name: '토켈라우',
    name_en: 'TOKELAU',
    name_origin: 'Tokelau',
    flag_path: 'TK.png',
    tel_code: '+690',
  },
  통가: {
    code_2: 'TO',
    code_3: 'TON',
    name: '통가',
    name_en: 'TONGA',
    name_origin: 'Tonga',
    flag_path: 'TO.png',
    tel_code: '+676',
  },
  투르크메니스탄: {
    code_2: 'TM',
    code_3: 'TKM',
    name: '투르크메니스탄',
    name_en: 'TURKMENISTAN',
    name_origin: 'Türkmenistan',
    flag_path: 'TM.png',
    tel_code: '+993',
  },
  투발루: {
    code_2: 'TV',
    code_3: 'TUV',
    name: '투발루',
    name_en: 'TUVALU',
    name_origin: 'Tuvalu',
    flag_path: 'TV.png',
    tel_code: '+688',
  },
  튀니지: {
    code_2: 'TN',
    code_3: 'TUN',
    name: '튀니지',
    name_en: 'TUNISIA',
    name_origin: 'تونس',
    flag_path: 'TN.png',
    tel_code: '+216',
  },
  '트리니다드 토바고': {
    code_2: 'TT',
    code_3: 'TTO',
    name: '트리니다드 토바고',
    name_en: 'TRINIDAD AND TOBAGO',
    name_origin: 'Trinidad and Tobago',
    flag_path: 'TT.png',
    tel_code: '+1868',
  },
  파나마: {
    code_2: 'PA',
    code_3: 'PAN',
    name: '파나마',
    name_en: 'PANAMA',
    name_origin: 'Panamá',
    flag_path: 'PA.png',
    tel_code: '+507',
  },
  파라과이: {
    code_2: 'PY',
    code_3: 'PRY',
    name: '파라과이',
    name_en: 'PARAGUAY',
    name_origin: 'Paraguay',
    flag_path: 'PY.png',
    tel_code: '+595',
  },
  파키스탄: {
    code_2: 'PK',
    code_3: 'PAK',
    name: '파키스탄',
    name_en: 'PAKISTAN',
    name_origin: 'پاکستان',
    flag_path: 'PK.png',
    tel_code: '+92',
  },
  '파푸아 뉴기니': {
    code_2: 'PG',
    code_3: 'PNG',
    name: '파푸아 뉴기니',
    name_en: 'PAPUA NEW GUINEA',
    name_origin: 'Papua New Guinea',
    flag_path: 'PG.png',
    tel_code: '+675',
  },
  팔라우: {
    code_2: 'PW',
    code_3: 'PLW',
    name: '팔라우',
    name_en: 'PALAU',
    name_origin: 'Belau',
    flag_path: 'PW.png',
    tel_code: '+680',
  },
  팔레스타인: {
    code_2: 'PS',
    code_3: 'PSE',
    name: '팔레스타인',
    name_en: 'PALESTINE',
    name_origin: 'Palestinian Territories',
    flag_path: 'PS.png',
    tel_code: '+970',
  },
  '페로 제도': {
    code_2: 'FO',
    code_3: 'FRO',
    name: '페로 제도',
    name_en: 'FAROE ISLANDS',
    name_origin: 'Faroe Islands',
    flag_path: 'FO.png',
    tel_code: '+298',
  },
  페루: {
    code_2: 'PE',
    code_3: 'PER',
    name: '페루',
    name_en: 'PERU',
    name_origin: 'Perú',
    flag_path: 'PE.png',
    tel_code: '+51',
  },
  포르투갈: {
    code_2: 'PT',
    code_3: 'PRT',
    name: '포르투갈',
    name_en: 'PORTUGAL',
    name_origin: 'Portugal',
    flag_path: 'PT.png',
    tel_code: '+351',
  },
  '포클랜드 제도': {
    code_2: 'FK',
    code_3: 'FLK',
    name: '포클랜드 제도',
    name_en: 'FALKLAND ISLANDS',
    name_origin: 'Falkland Islands',
    flag_path: 'FK.png',
    tel_code: '+500',
  },
  폴란드: {
    code_2: 'PL',
    code_3: 'POL',
    name: '폴란드',
    name_en: 'POLAND',
    name_origin: 'Polska',
    flag_path: 'PL.png',
    tel_code: '+48',
  },
  푸에르토리코: {
    code_2: 'PR',
    code_3: 'PRI',
    name: '푸에르토리코',
    name_en: 'PUERTO RICO',
    name_origin: 'Puerto Rico',
    flag_path: 'PR.png',
    tel_code: '+1787',
  },
  프랑스: {
    code_2: 'FR',
    code_3: 'FRA',
    name: '프랑스',
    name_en: 'FRANCE',
    name_origin: 'France',
    flag_path: 'FR.png',
    tel_code: '+33',
  },
  '프랑스령 기아나': {
    code_2: 'GF',
    code_3: 'GUF',
    name: '프랑스령 기아나',
    name_en: 'FRENCH GUIANA',
    name_origin: 'French Guiana',
    flag_path: 'GF.png',
    tel_code: '+594',
  },
  '프랑스령 남부와 남극 지역': {
    code_2: 'TF',
    code_3: 'ATF',
    name: '프랑스령 남부와 남극 지역',
    name_en: 'FRENCH SOUTHERN TERRITORIES',
    name_origin: 'French Southern Territories',
    flag_path: 'TF.png',
    tel_code: '+33',
  },
  '프랑스령 폴리네시아': {
    code_2: 'PF',
    code_3: 'PYF',
    name: '프랑스령 폴리네시아',
    name_en: 'FRENCH POLYNESIA',
    name_origin: 'French Polynesia',
    flag_path: 'PF.png',
    tel_code: '+689',
  },
};
