export enum CardVendorEnum {
  KAKAO = 'KAKAO',
  NAVER = 'NAVER',
  SAMSUNG = 'SAMSUNG',
  SHINHAN = 'SHINHAN',
  KB = 'KB',
  HYUNDAI = 'HYUNDAI',
  BC = 'BC',
  LOTTE = 'LOTTE',
  WOORI = 'WOORI',
  HANA = 'HANA',
  NH = 'NH',
  STANDARD = 'STANDARD',
  CITY = 'CITY',
  SUHYUP = 'SUHYUP',
  KEB = 'KEB',
  ETC = 'ETC',
}
