export enum ChargepointsFirmwareStatus {
  DOWNLOADED = 'DOWNLOADED',
  DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
  DOWNLOADING = 'DOWNLOADING',
  IDLE = 'IDLE',
  INSTALLATION_FAILED = 'INSTALLATION_FAILED',
  INSTALLING = 'INSTALLING',
  INSTALLED = 'INSTALLED',
}
