export enum PayMethod {
  NONE = 'NONE',
  CARD = 'CARD',
  BANK = 'BANK',
  VBANK = 'VBANK',
  CELLPHONE = 'CELLPHONE',
  NAVER = 'NAVER',
  KAKAO = 'KAKAO',
  PAYCO = 'PAYCO',
  PINPAY = 'PINPAY',
  SAMSUNGPAY = 'SAMSUNGPAY',
  TOSS = 'TOSS',
  LINEPAY = 'LINEPAY',
}
